// AUTO-GENERATED by script/gen-coach-catalog.ts — do not edit by hand.
// Compact pose catalog for the AI Yoga Coach compose endpoint (v4).
export type CoachPose = {
  slug: string;
  english: string;
  sanskrit: string;
  category: string;
  level: string;
  holdSeconds: number;
  benefits: string[];
  contraindications: string[];
  stretchZones: string[];
};

export const COACH_CATALOG: CoachPose[] = [
  {
    "slug": "tadasana",
    "english": "Mountain Pose",
    "sanskrit": "Tadasana",
    "category": "Standing",
    "level": "Beginner",
    "holdSeconds": 45,
    "benefits": [
      "Improves posture and body awareness",
      "Strengthens thighs, knees, and ankles",
      "Calms the mind and steadies the breath"
    ],
    "contraindications": [
      "Low blood pressure (rise slowly)",
      "Dizziness or vertigo"
    ],
    "stretchZones": [
      "Feet",
      "Spine",
      "Shoulders"
    ]
  },
  {
    "slug": "vrksasana",
    "english": "Tree Pose",
    "sanskrit": "Vrksasana",
    "category": "Standing",
    "level": "Beginner",
    "holdSeconds": 30,
    "benefits": [
      "Improves balance and concentration",
      "Strengthens ankles, calves, and core",
      "Opens the hips and chest"
    ],
    "contraindications": [
      "Recent ankle or knee injury",
      "Migraine or severe low blood pressure"
    ],
    "stretchZones": [
      "Standing ankle & calf",
      "Inner thigh",
      "Core"
    ]
  },
  {
    "slug": "virabhadrasana-ii",
    "english": "Warrior II",
    "sanskrit": "Virabhadrasana II",
    "category": "Standing",
    "level": "Beginner",
    "holdSeconds": 40,
    "benefits": [
      "Strengthens legs, glutes, and shoulders",
      "Opens the hips and chest",
      "Builds endurance and concentration"
    ],
    "contraindications": [
      "Knee injury (mind front-knee tracking)",
      "High blood pressure",
      "Diarrhea"
    ],
    "stretchZones": [
      "Front thigh & glute",
      "Inner thighs & groin",
      "Shoulders"
    ]
  },
  {
    "slug": "virabhadrasana-i",
    "english": "Warrior I",
    "sanskrit": "Virabhadrasana I",
    "category": "Standing",
    "level": "Intermediate",
    "holdSeconds": 40,
    "benefits": [
      "Strengthens legs and core",
      "Stretches hip flexors and chest",
      "Improves focus and balance"
    ],
    "contraindications": [
      "High blood pressure",
      "Shoulder issues (keep arms wider)",
      "Heart conditions"
    ],
    "stretchZones": [
      "Back-leg hip flexor",
      "Front thigh",
      "Chest & shoulders"
    ]
  },
  {
    "slug": "trikonasana",
    "english": "Triangle Pose",
    "sanskrit": "Trikonasana",
    "category": "Standing",
    "level": "Beginner",
    "holdSeconds": 40,
    "benefits": [
      "Stretches hamstrings, hips, and side body",
      "Strengthens legs and core",
      "Relieves back stiffness"
    ],
    "contraindications": [
      "Low blood pressure",
      "Neck issues (don't turn head up)",
      "Headache"
    ],
    "stretchZones": [
      "Front hamstring",
      "Side body",
      "Hips"
    ]
  },
  {
    "slug": "utkatasana",
    "english": "Chair Pose",
    "sanskrit": "Utkatasana",
    "category": "Standing",
    "level": "Beginner",
    "holdSeconds": 30,
    "benefits": [
      "Strengthens thighs, glutes, and ankles",
      "Tones the core",
      "Builds heat and stamina"
    ],
    "contraindications": [
      "Knee pain",
      "Low blood pressure",
      "Insomnia"
    ],
    "stretchZones": [
      "Thighs & quads",
      "Glutes",
      "Shoulders"
    ]
  },
  {
    "slug": "ardha-chandrasana",
    "english": "Half Moon Pose",
    "sanskrit": "Ardha Chandrasana",
    "category": "Standing",
    "level": "Intermediate",
    "holdSeconds": 25,
    "benefits": [
      "Strengthens ankles, legs, and core",
      "Improves balance and coordination",
      "Opens chest and hips"
    ],
    "contraindications": [
      "Low blood pressure",
      "Headache or migraine",
      "Neck injury"
    ],
    "stretchZones": [
      "Standing leg & hip",
      "Hamstring",
      "Chest & side body"
    ]
  },
  {
    "slug": "sukhasana",
    "english": "Easy Seat",
    "sanskrit": "Sukhasana",
    "category": "Seated",
    "level": "Beginner",
    "holdSeconds": 60,
    "benefits": [
      "Opens the hips",
      "Lengthens the spine",
      "Calms the nervous system"
    ],
    "contraindications": [
      "Knee injury (sit elevated)",
      "Sciatica"
    ],
    "stretchZones": [
      "Hips & outer hips",
      "Spine",
      "Knees"
    ]
  },
  {
    "slug": "padmasana",
    "english": "Lotus Pose",
    "sanskrit": "Padmasana",
    "category": "Seated",
    "level": "Advanced",
    "holdSeconds": 60,
    "benefits": [
      "Deeply opens hips",
      "Steadies the mind for meditation",
      "Improves posture"
    ],
    "contraindications": [
      "Knee or ankle injury",
      "Tight hips (use Half Lotus or Easy Seat instead)"
    ],
    "stretchZones": [
      "Hips",
      "Knees",
      "Ankles"
    ]
  },
  {
    "slug": "navasana",
    "english": "Boat Pose",
    "sanskrit": "Navasana",
    "category": "Seated",
    "level": "Intermediate",
    "holdSeconds": 25,
    "benefits": [
      "Strengthens the core and hip flexors",
      "Improves balance",
      "Tones the spine"
    ],
    "contraindications": [
      "Low back injury",
      "Pregnancy",
      "Recent abdominal surgery"
    ],
    "stretchZones": [
      "Core & abdominals",
      "Hip flexors",
      "Spine"
    ]
  },
  {
    "slug": "baddha-konasana",
    "english": "Butterfly / Bound Angle",
    "sanskrit": "Baddha Konasana",
    "category": "Hip Openers",
    "level": "Beginner",
    "holdSeconds": 60,
    "benefits": [
      "Opens hips and inner thighs",
      "Stimulates circulation",
      "Soothes the nervous system"
    ],
    "contraindications": [
      "Groin or knee injury",
      "Sciatica (sit elevated)"
    ],
    "stretchZones": [
      "Inner thighs & groin",
      "Hips",
      "Lower back"
    ]
  },
  {
    "slug": "eka-pada-rajakapotasana",
    "english": "Pigeon Pose",
    "sanskrit": "Eka Pada Rajakapotasana",
    "category": "Hip Openers",
    "level": "Intermediate",
    "holdSeconds": 60,
    "benefits": [
      "Opens hip rotators and glutes",
      "Stretches hip flexors of the back leg",
      "Releases low-back tension"
    ],
    "contraindications": [
      "Knee injury",
      "Sacroiliac issues",
      "Tight hips (use a prop)"
    ],
    "stretchZones": [
      "Front-leg outer hip & piriformis",
      "Back-leg hip flexor",
      "Lower back"
    ]
  },
  {
    "slug": "anjaneyasana",
    "english": "Low Lunge",
    "sanskrit": "Anjaneyasana",
    "category": "Hip Openers",
    "level": "Beginner",
    "holdSeconds": 45,
    "benefits": [
      "Stretches hip flexors and quadriceps",
      "Opens the chest",
      "Builds leg stability"
    ],
    "contraindications": [
      "Knee sensitivity (pad the back knee)",
      "High blood pressure (keep hands down)"
    ],
    "stretchZones": [
      "Back-leg hip flexor",
      "Quadriceps",
      "Chest"
    ]
  },
  {
    "slug": "utthan-pristhasana",
    "english": "Lizard Pose",
    "sanskrit": "Utthan Pristhasana",
    "category": "Hip Openers",
    "level": "Intermediate",
    "holdSeconds": 60,
    "benefits": [
      "Deeply opens hips and hip flexors",
      "Stretches hamstrings",
      "Prepares the body for splits"
    ],
    "contraindications": [
      "Knee or hip injury",
      "Recent groin strain"
    ],
    "stretchZones": [
      "Front hip & inner groin",
      "Hamstrings",
      "Back-leg hip flexor"
    ]
  },
  {
    "slug": "uttanasana",
    "english": "Standing Forward Fold",
    "sanskrit": "Uttanasana",
    "category": "Forward Bends",
    "level": "Beginner",
    "holdSeconds": 45,
    "benefits": [
      "Stretches hamstrings and calves",
      "Calms the mind",
      "Relieves tension in the neck and back"
    ],
    "contraindications": [
      "Low back injury (bend knees)",
      "High blood pressure",
      "Glaucoma"
    ],
    "stretchZones": [
      "Hamstrings",
      "Calves",
      "Neck & back"
    ]
  },
  {
    "slug": "paschimottanasana",
    "english": "Seated Forward Bend",
    "sanskrit": "Paschimottanasana",
    "category": "Forward Bends",
    "level": "Beginner",
    "holdSeconds": 60,
    "benefits": [
      "Stretches the entire back body",
      "Calms the nervous system",
      "Aids digestion"
    ],
    "contraindications": [
      "Low back injury",
      "Sciatica (sit elevated, bend knees)",
      "Asthma"
    ],
    "stretchZones": [
      "Hamstrings",
      "Lower back",
      "Calves"
    ]
  },
  {
    "slug": "parsvottanasana",
    "english": "Pyramid Pose",
    "sanskrit": "Parsvottanasana",
    "category": "Forward Bends",
    "level": "Intermediate",
    "holdSeconds": 40,
    "benefits": [
      "Deeply stretches hamstrings",
      "Improves balance",
      "Strengthens legs"
    ],
    "contraindications": [
      "High blood pressure",
      "Low back injury",
      "Hamstring tear"
    ],
    "stretchZones": [
      "Front-leg hamstring",
      "Hips",
      "Spine"
    ]
  },
  {
    "slug": "bhujangasana",
    "english": "Cobra Pose",
    "sanskrit": "Bhujangasana",
    "category": "Backbends",
    "level": "Beginner",
    "holdSeconds": 25,
    "benefits": [
      "Strengthens the spine",
      "Opens chest and shoulders",
      "Soothes sciatica"
    ],
    "contraindications": [
      "Back injury",
      "Pregnancy",
      "Carpal tunnel syndrome"
    ],
    "stretchZones": [
      "Spine & back",
      "Chest",
      "Abdominals"
    ]
  },
  {
    "slug": "setu-bandhasana",
    "english": "Bridge Pose",
    "sanskrit": "Setu Bandha Sarvangasana",
    "category": "Backbends",
    "level": "Beginner",
    "holdSeconds": 45,
    "benefits": [
      "Strengthens back, glutes, and hamstrings",
      "Opens the chest",
      "Calms the mind"
    ],
    "contraindications": [
      "Neck injury",
      "Shoulder issues"
    ],
    "stretchZones": [
      "Chest",
      "Hip flexors",
      "Back & glutes"
    ]
  },
  {
    "slug": "ustrasana",
    "english": "Camel Pose",
    "sanskrit": "Ustrasana",
    "category": "Backbends",
    "level": "Intermediate",
    "holdSeconds": 25,
    "benefits": [
      "Opens chest, abdomen, and hip flexors",
      "Strengthens the back",
      "Improves posture"
    ],
    "contraindications": [
      "Neck or low back injury",
      "High or low blood pressure",
      "Migraine"
    ],
    "stretchZones": [
      "Front body, chest & quads",
      "Shoulders",
      "Throat & front of neck"
    ]
  },
  {
    "slug": "urdhva-dhanurasana",
    "english": "Wheel Pose",
    "sanskrit": "Urdhva Dhanurasana",
    "category": "Backbends",
    "level": "Advanced",
    "holdSeconds": 20,
    "benefits": [
      "Deeply opens chest, shoulders, and hip flexors",
      "Strengthens arms, legs, and spine",
      "Energizes the body"
    ],
    "contraindications": [
      "Back, wrist, or shoulder injury",
      "High or low blood pressure",
      "Heart conditions"
    ],
    "stretchZones": [
      "Chest & shoulders",
      "Hip flexors",
      "Spine"
    ]
  },
  {
    "slug": "sirsasana",
    "english": "Headstand",
    "sanskrit": "Sirsasana",
    "category": "Inversions",
    "level": "Advanced",
    "holdSeconds": 45,
    "benefits": [
      "Strengthens the core and shoulders",
      "Improves circulation and focus",
      "Calms the mind"
    ],
    "contraindications": [
      "Neck injury",
      "High blood pressure",
      "Glaucoma",
      "Pregnancy"
    ],
    "stretchZones": [
      "Shoulders",
      "Core",
      "Neck"
    ]
  },
  {
    "slug": "adho-mukha-svanasana",
    "english": "Downward-Facing Dog",
    "sanskrit": "Adho Mukha Svanasana",
    "category": "Inversions",
    "level": "Beginner",
    "holdSeconds": 45,
    "benefits": [
      "Stretches hamstrings, calves, and shoulders",
      "Strengthens arms and legs",
      "Energizes the body"
    ],
    "contraindications": [
      "Wrist injury (carpal tunnel)",
      "High blood pressure",
      "Late pregnancy"
    ],
    "stretchZones": [
      "Hamstrings",
      "Calves",
      "Shoulders"
    ]
  },
  {
    "slug": "viparita-karani",
    "english": "Legs Up the Wall",
    "sanskrit": "Viparita Karani",
    "category": "Restorative",
    "level": "Beginner",
    "holdSeconds": 120,
    "benefits": [
      "Relieves tired legs and feet",
      "Calms the mind",
      "Eases mild anxiety and insomnia"
    ],
    "contraindications": [
      "Glaucoma",
      "Serious back or neck issues"
    ],
    "stretchZones": [
      "Legs & feet",
      "Lower back",
      "Nervous system"
    ]
  },
  {
    "slug": "balasana",
    "english": "Child's Pose",
    "sanskrit": "Balasana",
    "category": "Restorative",
    "level": "Beginner",
    "holdSeconds": 60,
    "benefits": [
      "Releases the back and hips",
      "Calms the nervous system",
      "Relieves fatigue"
    ],
    "contraindications": [
      "Knee injury",
      "Pregnancy (widen the knees)",
      "Recent ankle injury"
    ],
    "stretchZones": [
      "Lower back",
      "Hips",
      "Shoulders"
    ]
  },
  {
    "slug": "savasana",
    "english": "Corpse Pose",
    "sanskrit": "Savasana",
    "category": "Restorative",
    "level": "Beginner",
    "holdSeconds": 180,
    "benefits": [
      "Deeply relaxes body and mind",
      "Lowers stress and blood pressure",
      "Integrates the practice"
    ],
    "contraindications": [
      "Late pregnancy (lie on side)",
      "Low back discomfort (bend knees)"
    ],
    "stretchZones": [
      "Full body",
      "Nervous system"
    ]
  },
  {
    "slug": "ardha-hanumanasana",
    "english": "Half Split",
    "sanskrit": "Ardha Hanumanasana",
    "category": "Forward Bends",
    "level": "Intermediate",
    "holdSeconds": 60,
    "benefits": [
      "Stretches hamstrings and calves",
      "Prepares the body for Hanumanasana",
      "Lengthens the spine"
    ],
    "contraindications": [
      "Hamstring tear",
      "Knee sensitivity (pad the back knee)"
    ],
    "stretchZones": [
      "Front-leg hamstring",
      "Calf",
      "Lower back"
    ]
  },
  {
    "slug": "hanumanasana",
    "english": "Front Splits",
    "sanskrit": "Hanumanasana",
    "category": "Hip Openers",
    "level": "Advanced",
    "holdSeconds": 45,
    "benefits": [
      "Deeply stretches hamstrings and hip flexors",
      "Opens the entire lower body",
      "Builds focus and patience"
    ],
    "contraindications": [
      "Hamstring or groin injury",
      "Recent hip surgery",
      "Sacroiliac instability"
    ],
    "stretchZones": [
      "Front-leg hamstring",
      "Back-leg hip flexor & psoas",
      "Inner groin"
    ]
  },
  {
    "slug": "marichyasana-twist",
    "english": "Seated Twist",
    "sanskrit": "Marichyasana",
    "category": "Seated",
    "level": "Intermediate",
    "holdSeconds": 40,
    "benefits": [
      "Improves spinal mobility",
      "Aids digestion",
      "Relieves back tension"
    ],
    "contraindications": [
      "Spinal injury",
      "Pregnancy",
      "Recent abdominal surgery"
    ],
    "stretchZones": [
      "Spine",
      "Outer hip & glute",
      "Chest & shoulders"
    ]
  }
];

export const COACH_CATALOG_SLUGS = new Set(COACH_CATALOG.map((p) => p.slug));

// Compact one-line-per-pose JSON string bundled into the system prompt.
export const COACH_CATALOG_JSON = JSON.stringify(
  COACH_CATALOG.map((p) => ({
    slug: p.slug,
    english: p.english,
    sanskrit: p.sanskrit,
    category: p.category,
    level: p.level,
    holdSeconds: p.holdSeconds,
    benefits: p.benefits,
    contraindications: p.contraindications,
    stretchZones: p.stretchZones,
  })),
);
