// AUTO-GENERATED by script/gen-coach-catalog.ts — do not edit by hand.
// Compact pose catalog for the AI Yoga Coach compose endpoint (v4).
export type CoachPose = {
  slug: string;
  english: string;
  sanskrit: string;
  category: string;
  level: string;
  holdSeconds: number;
  benefits: string[];
  contraindications: string[];
  stretchZones: string[];
};

export const COACH_CATALOG: CoachPose[] = [
  {
    "slug": "tadasana",
    "english": "Mountain Pose",
    "sanskrit": "Tadasana",
    "category": "Standing",
    "level": "Beginner",
    "holdSeconds": 45,
    "benefits": [
      "Improves posture and body awareness",
      "Strengthens thighs, knees, and ankles",
      "Calms the mind and steadies the breath"
    ],
    "contraindications": [
      "Low blood pressure (rise slowly)",
      "Dizziness or vertigo"
    ],
    "stretchZones": [
      "Feet",
      "Spine",
      "Shoulders"
    ]
  },
  {
    "slug": "vrksasana",
    "english": "Tree Pose",
    "sanskrit": "Vrksasana",
    "category": "Standing",
    "level": "Beginner",
    "holdSeconds": 30,
    "benefits": [
      "Improves balance and concentration",
      "Strengthens ankles, calves, and core",
      "Opens the hips and chest"
    ],
    "contraindications": [
      "Recent ankle or knee injury",
      "Migraine or severe low blood pressure"
    ],
    "stretchZones": [
      "Standing ankle & calf",
      "Inner thigh",
      "Core"
    ]
  },
  {
    "slug": "virabhadrasana-ii",
    "english": "Warrior II",
    "sanskrit": "Virabhadrasana II",
    "category": "Standing",
    "level": "Beginner",
    "holdSeconds": 40,
    "benefits": [
      "Strengthens legs, glutes, and shoulders",
      "Opens the hips and chest",
      "Builds endurance and concentration"
    ],
    "contraindications": [
      "Knee injury (mind front-knee tracking)",
      "High blood pressure",
      "Diarrhea"
    ],
    "stretchZones": [
      "Front thigh & glute",
      "Inner thighs & groin",
      "Shoulders"
    ]
  },
  {
    "slug": "virabhadrasana-i",
    "english": "Warrior I",
    "sanskrit": "Virabhadrasana I",
    "category": "Standing",
    "level": "Intermediate",
    "holdSeconds": 40,
    "benefits": [
      "Strengthens legs and core",
      "Stretches hip flexors and chest",
      "Improves focus and balance"
    ],
    "contraindications": [
      "High blood pressure",
      "Shoulder issues (keep arms wider)",
      "Heart conditions"
    ],
    "stretchZones": [
      "Back-leg hip flexor",
      "Front thigh",
      "Chest & shoulders"
    ]
  },
  {
    "slug": "trikonasana",
    "english": "Triangle Pose",
    "sanskrit": "Trikonasana",
    "category": "Standing",
    "level": "Beginner",
    "holdSeconds": 40,
    "benefits": [
      "Stretches hamstrings, hips, and side body",
      "Strengthens legs and core",
      "Relieves back stiffness"
    ],
    "contraindications": [
      "Low blood pressure",
      "Neck issues (don't turn head up)",
      "Headache"
    ],
    "stretchZones": [
      "Front hamstring",
      "Side body",
      "Hips"
    ]
  },
  {
    "slug": "utkatasana",
    "english": "Chair Pose",
    "sanskrit": "Utkatasana",
    "category": "Standing",
    "level": "Beginner",
    "holdSeconds": 30,
    "benefits": [
      "Strengthens thighs, glutes, and ankles",
      "Tones the core",
      "Builds heat and stamina"
    ],
    "contraindications": [
      "Knee pain",
      "Low blood pressure",
      "Insomnia"
    ],
    "stretchZones": [
      "Thighs & quads",
      "Glutes",
      "Shoulders"
    ]
  },
  {
    "slug": "ardha-chandrasana",
    "english": "Half Moon Pose",
    "sanskrit": "Ardha Chandrasana",
    "category": "Standing",
    "level": "Intermediate",
    "holdSeconds": 25,
    "benefits": [
      "Strengthens ankles, legs, and core",
      "Improves balance and coordination",
      "Opens chest and hips"
    ],
    "contraindications": [
      "Low blood pressure",
      "Headache or migraine",
      "Neck injury"
    ],
    "stretchZones": [
      "Standing leg & hip",
      "Hamstring",
      "Chest & side body"
    ]
  },
  {
    "slug": "sukhasana",
    "english": "Easy Seat",
    "sanskrit": "Sukhasana",
    "category": "Seated",
    "level": "Beginner",
    "holdSeconds": 60,
    "benefits": [
      "Opens the hips",
      "Lengthens the spine",
      "Calms the nervous system"
    ],
    "contraindications": [
      "Knee injury (sit elevated)",
      "Sciatica"
    ],
    "stretchZones": [
      "Hips & outer hips",
      "Spine",
      "Knees"
    ]
  },
  {
    "slug": "padmasana",
    "english": "Lotus Pose",
    "sanskrit": "Padmasana",
    "category": "Seated",
    "level": "Advanced",
    "holdSeconds": 60,
    "benefits": [
      "Deeply opens hips",
      "Steadies the mind for meditation",
      "Improves posture"
    ],
    "contraindications": [
      "Knee or ankle injury",
      "Tight hips (use Half Lotus or Easy Seat instead)"
    ],
    "stretchZones": [
      "Hips",
      "Knees",
      "Ankles"
    ]
  },
  {
    "slug": "navasana",
    "english": "Boat Pose",
    "sanskrit": "Navasana",
    "category": "Seated",
    "level": "Intermediate",
    "holdSeconds": 25,
    "benefits": [
      "Strengthens the core and hip flexors",
      "Improves balance",
      "Tones the spine"
    ],
    "contraindications": [
      "Low back injury",
      "Pregnancy",
      "Recent abdominal surgery"
    ],
    "stretchZones": [
      "Core & abdominals",
      "Hip flexors",
      "Spine"
    ]
  },
  {
    "slug": "baddha-konasana",
    "english": "Butterfly / Bound Angle",
    "sanskrit": "Baddha Konasana",
    "category": "Hip Openers",
    "level": "Beginner",
    "holdSeconds": 60,
    "benefits": [
      "Opens hips and inner thighs",
      "Stimulates circulation",
      "Soothes the nervous system"
    ],
    "contraindications": [
      "Groin or knee injury",
      "Sciatica (sit elevated)"
    ],
    "stretchZones": [
      "Inner thighs & groin",
      "Hips",
      "Lower back"
    ]
  },
  {
    "slug": "eka-pada-rajakapotasana",
    "english": "Pigeon Pose",
    "sanskrit": "Eka Pada Rajakapotasana",
    "category": "Hip Openers",
    "level": "Intermediate",
    "holdSeconds": 60,
    "benefits": [
      "Opens hip rotators and glutes",
      "Stretches hip flexors of the back leg",
      "Releases low-back tension"
    ],
    "contraindications": [
      "Knee injury",
      "Sacroiliac issues",
      "Tight hips (use a prop)"
    ],
    "stretchZones": [
      "Front-leg outer hip & piriformis",
      "Back-leg hip flexor",
      "Lower back"
    ]
  },
  {
    "slug": "anjaneyasana",
    "english": "Low Lunge",
    "sanskrit": "Anjaneyasana",
    "category": "Hip Openers",
    "level": "Beginner",
    "holdSeconds": 45,
    "benefits": [
      "Stretches hip flexors and quadriceps",
      "Opens the chest",
      "Builds leg stability"
    ],
    "contraindications": [
      "Knee sensitivity (pad the back knee)",
      "High blood pressure (keep hands down)"
    ],
    "stretchZones": [
      "Back-leg hip flexor",
      "Quadriceps",
      "Chest"
    ]
  },
  {
    "slug": "utthan-pristhasana",
    "english": "Lizard Pose",
    "sanskrit": "Utthan Pristhasana",
    "category": "Hip Openers",
    "level": "Intermediate",
    "holdSeconds": 60,
    "benefits": [
      "Deeply opens hips and hip flexors",
      "Stretches hamstrings",
      "Prepares the body for splits"
    ],
    "contraindications": [
      "Knee or hip injury",
      "Recent groin strain"
    ],
    "stretchZones": [
      "Front hip & inner groin",
      "Hamstrings",
      "Back-leg hip flexor"
    ]
  },
  {
    "slug": "uttanasana",
    "english": "Standing Forward Fold",
    "sanskrit": "Uttanasana",
    "category": "Forward Bends",
    "level": "Beginner",
    "holdSeconds": 45,
    "benefits": [
      "Stretches hamstrings and calves",
      "Calms the mind",
      "Relieves tension in the neck and back"
    ],
    "contraindications": [
      "Low back injury (bend knees)",
      "High blood pressure",
      "Glaucoma"
    ],
    "stretchZones": [
      "Hamstrings",
      "Calves",
      "Neck & back"
    ]
  },
  {
    "slug": "paschimottanasana",
    "english": "Seated Forward Bend",
    "sanskrit": "Paschimottanasana",
    "category": "Forward Bends",
    "level": "Beginner",
    "holdSeconds": 60,
    "benefits": [
      "Stretches the entire back body",
      "Calms the nervous system",
      "Aids digestion"
    ],
    "contraindications": [
      "Low back injury",
      "Sciatica (sit elevated, bend knees)",
      "Asthma"
    ],
    "stretchZones": [
      "Hamstrings",
      "Lower back",
      "Calves"
    ]
  },
  {
    "slug": "parsvottanasana",
    "english": "Pyramid Pose",
    "sanskrit": "Parsvottanasana",
    "category": "Forward Bends",
    "level": "Intermediate",
    "holdSeconds": 40,
    "benefits": [
      "Deeply stretches hamstrings",
      "Improves balance",
      "Strengthens legs"
    ],
    "contraindications": [
      "High blood pressure",
      "Low back injury",
      "Hamstring tear"
    ],
    "stretchZones": [
      "Front-leg hamstring",
      "Hips",
      "Spine"
    ]
  },
  {
    "slug": "bhujangasana",
    "english": "Cobra Pose",
    "sanskrit": "Bhujangasana",
    "category": "Backbends",
    "level": "Beginner",
    "holdSeconds": 25,
    "benefits": [
      "Strengthens the spine",
      "Opens chest and shoulders",
      "Soothes sciatica"
    ],
    "contraindications": [
      "Back injury",
      "Pregnancy",
      "Carpal tunnel syndrome"
    ],
    "stretchZones": [
      "Spine & back",
      "Chest",
      "Abdominals"
    ]
  },
  {
    "slug": "setu-bandhasana",
    "english": "Bridge Pose",
    "sanskrit": "Setu Bandha Sarvangasana",
    "category": "Backbends",
    "level": "Beginner",
    "holdSeconds": 45,
    "benefits": [
      "Strengthens back, glutes, and hamstrings",
      "Opens the chest",
      "Calms the mind"
    ],
    "contraindications": [
      "Neck injury",
      "Shoulder issues"
    ],
    "stretchZones": [
      "Chest",
      "Hip flexors",
      "Back & glutes"
    ]
  },
  {
    "slug": "ustrasana",
    "english": "Camel Pose",
    "sanskrit": "Ustrasana",
    "category": "Backbends",
    "level": "Intermediate",
    "holdSeconds": 25,
    "benefits": [
      "Opens chest, abdomen, and hip flexors",
      "Strengthens the back",
      "Improves posture"
    ],
    "contraindications": [
      "Neck or low back injury",
      "High or low blood pressure",
      "Migraine"
    ],
    "stretchZones": [
      "Front body, chest & quads",
      "Shoulders",
      "Throat & front of neck"
    ]
  },
  {
    "slug": "urdhva-dhanurasana",
    "english": "Wheel Pose",
    "sanskrit": "Urdhva Dhanurasana",
    "category": "Backbends",
    "level": "Advanced",
    "holdSeconds": 20,
    "benefits": [
      "Deeply opens chest, shoulders, and hip flexors",
      "Strengthens arms, legs, and spine",
      "Energizes the body"
    ],
    "contraindications": [
      "Back, wrist, or shoulder injury",
      "High or low blood pressure",
      "Heart conditions"
    ],
    "stretchZones": [
      "Chest & shoulders",
      "Hip flexors",
      "Spine"
    ]
  },
  {
    "slug": "sirsasana",
    "english": "Headstand",
    "sanskrit": "Sirsasana",
    "category": "Inversions",
    "level": "Advanced",
    "holdSeconds": 45,
    "benefits": [
      "Strengthens the core and shoulders",
      "Improves circulation and focus",
      "Calms the mind"
    ],
    "contraindications": [
      "Neck injury",
      "High blood pressure",
      "Glaucoma",
      "Pregnancy"
    ],
    "stretchZones": [
      "Shoulders",
      "Core",
      "Neck"
    ]
  },
  {
    "slug": "adho-mukha-svanasana",
    "english": "Downward-Facing Dog",
    "sanskrit": "Adho Mukha Svanasana",
    "category": "Inversions",
    "level": "Beginner",
    "holdSeconds": 45,
    "benefits": [
      "Stretches hamstrings, calves, and shoulders",
      "Strengthens arms and legs",
      "Energizes the body"
    ],
    "contraindications": [
      "Wrist injury (carpal tunnel)",
      "High blood pressure",
      "Late pregnancy"
    ],
    "stretchZones": [
      "Hamstrings",
      "Calves",
      "Shoulders"
    ]
  },
  {
    "slug": "viparita-karani",
    "english": "Legs Up the Wall",
    "sanskrit": "Viparita Karani",
    "category": "Restorative",
    "level": "Beginner",
    "holdSeconds": 120,
    "benefits": [
      "Relieves tired legs and feet",
      "Calms the mind",
      "Eases mild anxiety and insomnia"
    ],
    "contraindications": [
      "Glaucoma",
      "Serious back or neck issues"
    ],
    "stretchZones": [
      "Legs & feet",
      "Lower back",
      "Nervous system"
    ]
  },
  {
    "slug": "balasana",
    "english": "Child's Pose",
    "sanskrit": "Balasana",
    "category": "Restorative",
    "level": "Beginner",
    "holdSeconds": 60,
    "benefits": [
      "Releases the back and hips",
      "Calms the nervous system",
      "Relieves fatigue"
    ],
    "contraindications": [
      "Knee injury",
      "Pregnancy (widen the knees)",
      "Recent ankle injury"
    ],
    "stretchZones": [
      "Lower back",
      "Hips",
      "Shoulders"
    ]
  },
  {
    "slug": "savasana",
    "english": "Corpse Pose",
    "sanskrit": "Savasana",
    "category": "Restorative",
    "level": "Beginner",
    "holdSeconds": 180,
    "benefits": [
      "Deeply relaxes body and mind",
      "Lowers stress and blood pressure",
      "Integrates the practice"
    ],
    "contraindications": [
      "Late pregnancy (lie on side)",
      "Low back discomfort (bend knees)"
    ],
    "stretchZones": [
      "Full body",
      "Nervous system"
    ]
  },
  {
    "slug": "ardha-hanumanasana",
    "english": "Half Split",
    "sanskrit": "Ardha Hanumanasana",
    "category": "Forward Bends",
    "level": "Intermediate",
    "holdSeconds": 60,
    "benefits": [
      "Stretches hamstrings and calves",
      "Prepares the body for Hanumanasana",
      "Lengthens the spine"
    ],
    "contraindications": [
      "Hamstring tear",
      "Knee sensitivity (pad the back knee)"
    ],
    "stretchZones": [
      "Front-leg hamstring",
      "Calf",
      "Lower back"
    ]
  },
  {
    "slug": "hanumanasana",
    "english": "Front Splits",
    "sanskrit": "Hanumanasana",
    "category": "Hip Openers",
    "level": "Advanced",
    "holdSeconds": 45,
    "benefits": [
      "Deeply stretches hamstrings and hip flexors",
      "Opens the entire lower body",
      "Builds focus and patience"
    ],
    "contraindications": [
      "Hamstring or groin injury",
      "Recent hip surgery",
      "Sacroiliac instability"
    ],
    "stretchZones": [
      "Front-leg hamstring",
      "Back-leg hip flexor & psoas",
      "Inner groin"
    ]
  },
  {
    "slug": "marichyasana-twist",
    "english": "Seated Twist",
    "sanskrit": "Marichyasana",
    "category": "Seated",
    "level": "Intermediate",
    "holdSeconds": 40,
    "benefits": [
      "Improves spinal mobility",
      "Aids digestion",
      "Relieves back tension"
    ],
    "contraindications": [
      "Spinal injury",
      "Pregnancy",
      "Recent abdominal surgery"
    ],
    "stretchZones": [
      "Spine",
      "Outer hip & glute",
      "Chest & shoulders"
    ]
  },
  {
    "slug": "virabhadrasana-iii",
    "english": "Warrior III",
    "sanskrit": "Virabhadrasana III",
    "category": "Standing",
    "level": "Intermediate",
    "holdSeconds": 30,
    "benefits": [
      "Builds balance, focus, and full-body coordination",
      "Strengthens the standing leg, glutes, and back",
      "Tones the core and improves posture"
    ],
    "contraindications": [
      "High blood pressure",
      "Recent ankle or knee injury",
      "Low balance or dizziness (use a wall)"
    ],
    "stretchZones": [
      "Standing leg & glute",
      "Back & core",
      "Lifted-leg hamstring"
    ]
  },
  {
    "slug": "utthita-parsvakonasana",
    "english": "Extended Side Angle",
    "sanskrit": "Utthita Parsvakonasana",
    "category": "Standing",
    "level": "Intermediate",
    "holdSeconds": 40,
    "benefits": [
      "Stretches the side body, groin, and hamstrings",
      "Strengthens the legs, knees, and ankles",
      "Opens the chest and shoulders"
    ],
    "contraindications": [
      "Knee injury (mind front-knee tracking)",
      "High or low blood pressure",
      "Headache or insomnia"
    ],
    "stretchZones": [
      "Side body & waist",
      "Front thigh & groin",
      "Chest & shoulders"
    ]
  },
  {
    "slug": "urdhva-prasarita-eka-padasana",
    "english": "Standing Split",
    "sanskrit": "Urdhva Prasarita Eka Padasana",
    "category": "Standing",
    "level": "Advanced",
    "holdSeconds": 30,
    "benefits": [
      "Deeply stretches the standing-leg hamstring",
      "Builds balance and hip mobility",
      "Strengthens the standing leg and calms the mind"
    ],
    "contraindications": [
      "Hamstring tear or strain",
      "Dizzy spells or low blood pressure",
      "Ankle instability"
    ],
    "stretchZones": [
      "Standing-leg hamstring",
      "Hips",
      "Standing ankle & calf"
    ]
  },
  {
    "slug": "garudasana",
    "english": "Eagle Pose",
    "sanskrit": "Garudasana",
    "category": "Standing",
    "level": "Intermediate",
    "holdSeconds": 30,
    "benefits": [
      "Improves balance and concentration",
      "Stretches the shoulders, upper back, and outer hips",
      "Strengthens the ankles and thighs"
    ],
    "contraindications": [
      "Knee injury (don't hook the foot)",
      "Shoulder injury",
      "Low balance (practice near a wall)"
    ],
    "stretchZones": [
      "Upper back & shoulders",
      "Outer hips",
      "Ankles & thighs"
    ]
  },
  {
    "slug": "gomukhasana",
    "english": "Cow Face Pose",
    "sanskrit": "Gomukhasana",
    "category": "Seated",
    "level": "Intermediate",
    "holdSeconds": 40,
    "benefits": [
      "Opens the shoulders, chest, and triceps",
      "Stretches the outer hips and thighs",
      "Improves posture and upper-body mobility"
    ],
    "contraindications": [
      "Serious shoulder or knee injury",
      "Neck problems (keep the head neutral)"
    ],
    "stretchZones": [
      "Shoulders & triceps",
      "Outer hips & thighs",
      "Chest"
    ]
  },
  {
    "slug": "bharadvajasana",
    "english": "Bharadvaja's Twist",
    "sanskrit": "Bharadvajasana",
    "category": "Seated",
    "level": "Beginner",
    "holdSeconds": 40,
    "benefits": [
      "Gently mobilizes the whole spine",
      "Eases lower-back and neck tension",
      "Aids digestion and calms the mind"
    ],
    "contraindications": [
      "Recent back surgery",
      "Pregnancy (keep it extremely gentle, twisting open)",
      "Acute low-back pain"
    ],
    "stretchZones": [
      "Spine",
      "Outer hips",
      "Chest & shoulders"
    ]
  },
  {
    "slug": "janu-sirsasana",
    "english": "Head-to-Knee Pose",
    "sanskrit": "Janu Sirsasana",
    "category": "Forward Bends",
    "level": "Beginner",
    "holdSeconds": 60,
    "benefits": [
      "Stretches the hamstrings, spine, and outer hip",
      "Calms the nervous system and eases mild anxiety",
      "Improves digestion and flexibility"
    ],
    "contraindications": [
      "Knee injury (support the bent knee)",
      "Acute low-back injury",
      "Diarrhea"
    ],
    "stretchZones": [
      "Extended-leg hamstring",
      "Spine & lower back",
      "Bent-leg outer hip"
    ]
  },
  {
    "slug": "dhanurasana",
    "english": "Bow Pose",
    "sanskrit": "Dhanurasana",
    "category": "Backbends",
    "level": "Intermediate",
    "holdSeconds": 30,
    "benefits": [
      "Opens the entire front body and chest",
      "Strengthens the back muscles and legs",
      "Stretches the hip flexors, quads, and shoulders"
    ],
    "contraindications": [
      "Pregnancy",
      "Wrist injury",
      "High blood pressure",
      "Hernia",
      "Recent abdominal surgery"
    ],
    "stretchZones": [
      "Front body",
      "Quadriceps",
      "Shoulders"
    ]
  },
  {
    "slug": "salabhasana",
    "english": "Locust Pose",
    "sanskrit": "Salabhasana",
    "category": "Backbends",
    "level": "Beginner",
    "holdSeconds": 30,
    "benefits": [
      "Strengthens the back, glutes, and hamstrings",
      "Improves posture and spinal endurance",
      "Gently opens the chest and shoulders"
    ],
    "contraindications": [
      "Pregnancy after the first trimester",
      "Recent abdominal or back surgery",
      "Serious low-back injury"
    ],
    "stretchZones": [
      "Lower back & spine",
      "Glutes & hamstrings",
      "Chest"
    ]
  },
  {
    "slug": "matsyasana",
    "english": "Fish Pose",
    "sanskrit": "Matsyasana",
    "category": "Backbends",
    "level": "Intermediate",
    "holdSeconds": 40,
    "benefits": [
      "Opens the chest, throat, and front of the neck",
      "Counters rounded shoulders and desk posture",
      "Stretches the hip flexors and intercostal muscles"
    ],
    "contraindications": [
      "Neck injury",
      "High or low blood pressure",
      "Migraine or headache"
    ],
    "stretchZones": [
      "Chest & throat",
      "Upper back",
      "Hip flexors"
    ]
  },
  {
    "slug": "mandukasana",
    "english": "Frog Pose",
    "sanskrit": "Mandukasana",
    "category": "Hip Openers",
    "level": "Intermediate",
    "holdSeconds": 75,
    "benefits": [
      "Deeply opens the inner thighs and adductors",
      "Increases hip mobility and external rotation",
      "Relieves tension in the groin and lower back"
    ],
    "contraindications": [
      "Knee injury",
      "Groin strain",
      "Pregnancy"
    ],
    "stretchZones": [
      "Inner thighs & adductors",
      "Hips",
      "Lower back"
    ]
  },
  {
    "slug": "ananda-balasana",
    "english": "Happy Baby Pose",
    "sanskrit": "Ananda Balasana",
    "category": "Hip Openers",
    "level": "Beginner",
    "holdSeconds": 75,
    "benefits": [
      "Gently opens the hips and inner thighs",
      "Releases the lower back and sacrum",
      "Calms the mind and relieves fatigue"
    ],
    "contraindications": [
      "Neck injury (keep the head down)",
      "Pregnancy (use a wide-knee variation)",
      "Recent hip or knee injury"
    ],
    "stretchZones": [
      "Inner thighs & groin",
      "Lower back & sacrum",
      "Hips"
    ]
  },
  {
    "slug": "prasarita-padottanasana",
    "english": "Wide-Legged Forward Fold",
    "sanskrit": "Prasarita Padottanasana",
    "category": "Forward Bends",
    "level": "Beginner",
    "holdSeconds": 60,
    "benefits": [
      "Stretches the hamstrings and inner legs",
      "Releases the spine, neck, and shoulders",
      "Calms the mind and relieves mild fatigue"
    ],
    "contraindications": [
      "Low-back injury (keep a slight bend, come up slowly)",
      "Very low blood pressure",
      "Hamstring tear"
    ],
    "stretchZones": [
      "Hamstrings",
      "Spine & back",
      "Neck & shoulders"
    ]
  },
  {
    "slug": "kumbhakasana",
    "english": "Plank Pose",
    "sanskrit": "Kumbhakasana",
    "category": "Standing",
    "level": "Beginner",
    "holdSeconds": 45,
    "benefits": [
      "Strengthens the core, arms, wrists, and shoulders",
      "Builds full-body stability and endurance",
      "Improves posture and spinal support"
    ],
    "contraindications": [
      "Wrist injury (drop to the forearms)",
      "Pregnancy after the second trimester",
      "Serious shoulder injury"
    ],
    "stretchZones": [
      "Core & abdominals",
      "Shoulders & arms",
      "Wrists"
    ]
  },
  {
    "slug": "vasisthasana",
    "english": "Side Plank Pose",
    "sanskrit": "Vasisthasana",
    "category": "Standing",
    "level": "Intermediate",
    "holdSeconds": 30,
    "benefits": [
      "Strengthens the obliques, wrists, and shoulders",
      "Builds balance and core stability",
      "Tones the arms and improves focus"
    ],
    "contraindications": [
      "Wrist injury (use the forearm version)",
      "Pregnancy after the second trimester",
      "Shoulder injury"
    ],
    "stretchZones": [
      "Obliques & side core",
      "Supporting shoulder & wrist",
      "Chest"
    ]
  },
  {
    "slug": "utkata-konasana",
    "english": "Goddess Pose",
    "sanskrit": "Utkata Konasana",
    "category": "Standing",
    "level": "Beginner",
    "holdSeconds": 45,
    "benefits": [
      "Strengthens the legs, glutes, and pelvic floor",
      "Opens the hips and inner thighs",
      "Builds heat, stamina, and a sense of empowerment"
    ],
    "contraindications": [
      "Knee injury (narrow the stance)",
      "Late pregnancy (mind balance)",
      "Hip injury"
    ],
    "stretchZones": [
      "Inner thighs & groin",
      "Quads & glutes",
      "Pelvic floor & hips"
    ]
  },
  {
    "slug": "viparita-virabhadrasana",
    "english": "Reverse Warrior",
    "sanskrit": "Viparita Virabhadrasana",
    "category": "Standing",
    "level": "Beginner",
    "holdSeconds": 30,
    "benefits": [
      "Stretches the side body, waist, and intercostals",
      "Strengthens the legs and opens the chest",
      "Improves spinal mobility and breath capacity"
    ],
    "contraindications": [
      "Hip or knee injury",
      "Low back injury (keep the arc gentle)",
      "High blood pressure"
    ],
    "stretchZones": [
      "Side body & waist",
      "Front thigh",
      "Chest & shoulders"
    ]
  },
  {
    "slug": "chaturanga-dandasana",
    "english": "Four-Limbed Staff Pose",
    "sanskrit": "Chaturanga Dandasana",
    "category": "Standing",
    "level": "Intermediate",
    "holdSeconds": 8,
    "benefits": [
      "Builds tremendous arm, shoulder, and core strength",
      "Teaches precise shoulder alignment",
      "Prepares the body for arm balances"
    ],
    "contraindications": [
      "Wrist injury",
      "Shoulder impingement",
      "Pregnancy (2nd trimester onward)"
    ],
    "stretchZones": [
      "Shoulders & triceps",
      "Core & abdominals",
      "Wrists"
    ]
  },
  {
    "slug": "urdhva-mukha-svanasana",
    "english": "Upward-Facing Dog",
    "sanskrit": "Urdhva Mukha Svanasana",
    "category": "Backbends",
    "level": "Intermediate",
    "holdSeconds": 20,
    "benefits": [
      "Opens the chest, shoulders, and abdomen",
      "Strengthens the arms, wrists, and spine",
      "Improves posture and counteracts slumping"
    ],
    "contraindications": [
      "Lower back injury",
      "Carpal tunnel syndrome",
      "Pregnancy (2nd trimester onward)"
    ],
    "stretchZones": [
      "Chest & abdomen",
      "Shoulders",
      "Spine"
    ]
  },
  {
    "slug": "marjaryasana-bitilasana",
    "english": "Cat-Cow",
    "sanskrit": "Marjaryasana-Bitilasana",
    "category": "Restorative",
    "level": "Beginner",
    "holdSeconds": 60,
    "benefits": [
      "Mobilizes the whole spine, vertebra by vertebra",
      "Warms up the back before deeper practice",
      "Links breath and movement to settle a busy mind"
    ],
    "contraindications": [
      "Wrist pain (practice on fists or forearms)",
      "Recent spinal injury",
      "Knee sensitivity (pad the knees)"
    ],
    "stretchZones": [
      "Spine",
      "Core & belly",
      "Neck"
    ]
  },
  {
    "slug": "supta-matsyendrasana",
    "english": "Supine Twist",
    "sanskrit": "Supta Matsyendrasana",
    "category": "Restorative",
    "level": "Beginner",
    "holdSeconds": 60,
    "benefits": [
      "Releases the lower back and outer hips",
      "Gently massages the abdominal organs",
      "Downshifts the nervous system before sleep"
    ],
    "contraindications": [
      "Recent spinal or hip surgery",
      "Late pregnancy (twist from the upper back only)",
      "Sacroiliac joint pain"
    ],
    "stretchZones": [
      "Lower back",
      "Outer hip",
      "Chest"
    ]
  },
  {
    "slug": "supta-kapotasana",
    "english": "Reclined Figure-Four",
    "sanskrit": "Supta Kapotasana",
    "category": "Hip Openers",
    "level": "Beginner",
    "holdSeconds": 45,
    "benefits": [
      "Opens the outer hips and glutes deeply but safely",
      "Relieves sciatic and lower-back tension",
      "Perfect after running, cycling, or long sitting"
    ],
    "contraindications": [
      "Recent knee ligament injury",
      "Recent hip replacement (consult your provider)"
    ],
    "stretchZones": [
      "Outer hip & glute",
      "Lower back"
    ]
  },
  {
    "slug": "parsva-balasana",
    "english": "Thread the Needle",
    "sanskrit": "Parsva Balasana",
    "category": "Restorative",
    "level": "Beginner",
    "holdSeconds": 45,
    "benefits": [
      "Releases the upper back and rear shoulder",
      "Gently twists the thoracic spine, where desk stiffness lives",
      "Calms the nervous system with the head supported"
    ],
    "contraindications": [
      "Neck injury (keep the head supported on a block)",
      "Shoulder instability",
      "Knee sensitivity (pad the knees)"
    ],
    "stretchZones": [
      "Upper back",
      "Rear shoulder",
      "Neck"
    ]
  },
  {
    "slug": "uttana-shishosana",
    "english": "Puppy Pose",
    "sanskrit": "Uttana Shishosana",
    "category": "Backbends",
    "level": "Beginner",
    "holdSeconds": 45,
    "benefits": [
      "Opens the shoulders, chest, and armpits",
      "Lengthens the spine without loading the lower back",
      "A gentle first step toward deeper backbends"
    ],
    "contraindications": [
      "Shoulder injury",
      "Knee pain (pad the knees)",
      "Late pregnancy (keep the belly comfortable)"
    ],
    "stretchZones": [
      "Shoulders & armpits",
      "Chest",
      "Mid back"
    ]
  },
  {
    "slug": "malasana",
    "english": "Garland Pose",
    "sanskrit": "Malasana",
    "category": "Hip Openers",
    "level": "Beginner",
    "holdSeconds": 45,
    "benefits": [
      "Opens the hips, groin, and ankles all at once",
      "Counteracts the effects of long sitting",
      "Builds the foundation for splits and deeper hip work"
    ],
    "contraindications": [
      "Knee injury (sit on a block instead)",
      "Achilles or ankle injury",
      "Recent hip surgery"
    ],
    "stretchZones": [
      "Hips & groin",
      "Ankles",
      "Lower back"
    ]
  },
  {
    "slug": "virasana",
    "english": "Hero Pose",
    "sanskrit": "Virasana",
    "category": "Seated",
    "level": "Beginner",
    "holdSeconds": 60,
    "benefits": [
      "Stretches the thighs, knees, and ankles",
      "A steadier meditation seat than crossed legs for many bodies",
      "Improves posture through a naturally upright pelvis"
    ],
    "contraindications": [
      "Knee ligament injury (elevate the seat well)",
      "Ankle injury",
      "Numbness in the legs - come out and shake them free"
    ],
    "stretchZones": [
      "Front thighs",
      "Ankles & feet",
      "Knees"
    ]
  },
  {
    "slug": "supta-baddha-konasana",
    "english": "Reclining Butterfly",
    "sanskrit": "Supta Baddha Konasana",
    "category": "Restorative",
    "level": "Beginner",
    "holdSeconds": 90,
    "benefits": [
      "Opens the inner thighs and groin passively",
      "Deeply calming for the nervous system",
      "A favorite for winding down before sleep"
    ],
    "contraindications": [
      "Groin or knee strain (support the thighs well)",
      "Lower-back discomfort (elevate the torso on a bolster)"
    ],
    "stretchZones": [
      "Inner thighs & groin",
      "Chest",
      "Whole body"
    ]
  },
  {
    "slug": "ardha-matsyendrasana",
    "english": "Half Lord of the Fishes",
    "sanskrit": "Ardha Matsyendrasana",
    "category": "Seated",
    "level": "Intermediate",
    "holdSeconds": 45,
    "benefits": [
      "Increases spinal mobility and digestion",
      "Releases mid-back and shoulder tension",
      "Improves posture after long sitting"
    ],
    "contraindications": [
      "Recent spinal surgery",
      "Herniated disc (keep the twist mild)",
      "Late pregnancy"
    ],
    "stretchZones": [
      "Spine & mid-back",
      "Outer hip",
      "Shoulders"
    ]
  },
  {
    "slug": "upavistha-konasana",
    "english": "Wide-Angle Seated Forward Bend",
    "sanskrit": "Upavistha Konasana",
    "category": "Forward Bends",
    "level": "Beginner",
    "holdSeconds": 60,
    "benefits": [
      "Stretches hamstrings, adductors, and lower back",
      "Calms the nervous system",
      "Prepares the hips for deeper seated work"
    ],
    "contraindications": [
      "Hamstring tear",
      "Groin injury",
      "Lower-back disc issues (fold less and sit higher)"
    ],
    "stretchZones": [
      "Inner thighs",
      "Hamstrings",
      "Lower back"
    ]
  },
  {
    "slug": "halasana",
    "english": "Plow Pose",
    "sanskrit": "Halasana",
    "category": "Inversions",
    "level": "Intermediate",
    "holdSeconds": 45,
    "benefits": [
      "Stretches the spine, shoulders, and hamstrings",
      "Stimulates the thyroid and calming nervous tone",
      "Relieves fatigue when practiced gently"
    ],
    "contraindications": [
      "Neck injury",
      "Glaucoma or high blood pressure",
      "Menstruation (skip deep inversions)",
      "Pregnancy"
    ],
    "stretchZones": [
      "Spine & back body",
      "Shoulders",
      "Hamstrings"
    ]
  },
  {
    "slug": "sarvangasana",
    "english": "Shoulder Stand",
    "sanskrit": "Salamba Sarvangasana",
    "category": "Inversions",
    "level": "Intermediate",
    "holdSeconds": 45,
    "benefits": [
      "Strengthens shoulders, arms, and core",
      "Improves circulation and focus",
      "Deeply calming when held with support"
    ],
    "contraindications": [
      "Neck injury",
      "Glaucoma",
      "High blood pressure",
      "Menstruation",
      "Pregnancy"
    ],
    "stretchZones": [
      "Shoulders & upper arms",
      "Core",
      "Neck"
    ]
  },
  {
    "slug": "bakasana",
    "english": "Crow Pose",
    "sanskrit": "Bakasana",
    "category": "Standing",
    "level": "Advanced",
    "holdSeconds": 20,
    "benefits": [
      "Strengthens arms, wrists, and core",
      "Improves balance and concentration",
      "Builds confidence for deeper arm balances"
    ],
    "contraindications": [
      "Wrist injury",
      "Shoulder instability",
      "Pregnancy",
      "Recent carpal tunnel flare"
    ],
    "stretchZones": [
      "Arms & wrists",
      "Core",
      "Inner thighs"
    ]
  },
  {
    "slug": "parivrtta-anjaneyasana",
    "english": "Revolved Low Lunge",
    "sanskrit": "Parivrtta Anjaneyasana",
    "category": "Standing",
    "level": "Intermediate",
    "holdSeconds": 30,
    "benefits": [
      "Opens hip flexors and chest",
      "Builds balance and spinal mobility",
      "Energizes a sluggish mid-day body"
    ],
    "contraindications": [
      "Knee injury (pad generously)",
      "Recent spinal injury",
      "Late pregnancy"
    ],
    "stretchZones": [
      "Hip flexors",
      "Spine",
      "Chest"
    ]
  },
  {
    "slug": "purvottanasana",
    "english": "Upward Plank",
    "sanskrit": "Purvottanasana",
    "category": "Backbends",
    "level": "Intermediate",
    "holdSeconds": 30,
    "benefits": [
      "Strengthens wrists, arms, and posterior chain",
      "Opens the chest and shoulders",
      "Counters long hours of sitting and typing"
    ],
    "contraindications": [
      "Wrist injury",
      "Shoulder injury",
      "Neck pain (keep the head neutral)"
    ],
    "stretchZones": [
      "Front body",
      "Arms & wrists",
      "Glutes & hamstrings"
    ]
  },
  {
    "slug": "apanasana",
    "english": "Knees-to-Chest Pose",
    "sanskrit": "Apanasana",
    "category": "Restorative",
    "level": "Beginner",
    "holdSeconds": 60,
    "benefits": [
      "Relieves lower-back tension",
      "Gently massages the abdominal organs",
      "A reset button between stronger poses"
    ],
    "contraindications": [
      "Recent abdominal surgery",
      "Late pregnancy (widen the knees)",
      "Severe knee issues"
    ],
    "stretchZones": [
      "Lower back",
      "Hips",
      "Belly"
    ]
  },
  {
    "slug": "supta-padangusthasana",
    "english": "Reclined Hand-to-Big-Toe",
    "sanskrit": "Supta Padangusthasana",
    "category": "Forward Bends",
    "level": "Beginner",
    "holdSeconds": 45,
    "benefits": [
      "Lengthens hamstrings and calves safely",
      "Relieves sciatic tension for many bodies",
      "Improves leg flexibility for standing folds"
    ],
    "contraindications": [
      "Hamstring tear",
      "Acute sciatica (keep the stretch mild)",
      "Unstable SI joint"
    ],
    "stretchZones": [
      "Hamstrings",
      "Calves",
      "Hip"
    ]
  },
  {
    "slug": "parighasana",
    "english": "Gate Pose",
    "sanskrit": "Parighasana",
    "category": "Standing",
    "level": "Beginner",
    "holdSeconds": 30,
    "benefits": [
      "Stretches the side body and intercostals",
      "Opens the outer hip and hamstring of the extended leg",
      "Improves breathing capacity"
    ],
    "contraindications": [
      "Knee injury (pad well or practice seated)",
      "Recent rib injury"
    ],
    "stretchZones": [
      "Side body",
      "Inner thigh",
      "Ribs"
    ]
  },
  {
    "slug": "ardha-pincha-mayurasana",
    "english": "Dolphin Pose",
    "sanskrit": "Ardha Pincha Mayurasana",
    "category": "Inversions",
    "level": "Intermediate",
    "holdSeconds": 45,
    "benefits": [
      "Builds shoulder and upper-back strength",
      "Stretches hamstrings and calves",
      "Safe prep for forearm stand and headstand"
    ],
    "contraindications": [
      "Shoulder injury",
      "Wrist-free alternative still loads elbows — ease off if painful",
      "High blood pressure (keep the head high)"
    ],
    "stretchZones": [
      "Shoulders",
      "Hamstrings",
      "Upper back"
    ]
  },
  {
    "slug": "parivrtta-trikonasana",
    "english": "Revolved Triangle",
    "sanskrit": "Parivrtta Trikonasana",
    "category": "Standing",
    "level": "Intermediate",
    "holdSeconds": 30,
    "benefits": [
      "Improves balance and proprioception",
      "Stretches hamstrings and IT band",
      "Strengthens legs and deep core"
    ],
    "contraindications": [
      "Low back injury",
      "Tight hamstrings (use a block)",
      "Migraine or dizziness"
    ],
    "stretchZones": [
      "Hamstrings",
      "Spine",
      "Standing legs"
    ]
  },
  {
    "slug": "natarajasana",
    "english": "Dancer Pose",
    "sanskrit": "Natarajasana",
    "category": "Standing",
    "level": "Intermediate",
    "holdSeconds": 30,
    "benefits": [
      "Improves balance and focus",
      "Opens the chest, shoulders, and hip flexors",
      "Strengthens the standing leg"
    ],
    "contraindications": [
      "Ankle or knee instability",
      "Low back pain (kick less)",
      "Shoulder injury"
    ],
    "stretchZones": [
      "Standing leg",
      "Hip flexors & chest",
      "Shoulders"
    ]
  },
  {
    "slug": "agnistambhasana",
    "english": "Fire Log Pose",
    "sanskrit": "Agnistambhasana",
    "category": "Hip Openers",
    "level": "Intermediate",
    "holdSeconds": 60,
    "benefits": [
      "Deeply opens the outer hips and glutes",
      "Relieves tension from sitting and running",
      "Prepares the hips for lotus and pigeon variations"
    ],
    "contraindications": [
      "Knee injury (never force the stack)",
      "Hip replacement",
      "Acute SI joint pain"
    ],
    "stretchZones": [
      "Outer hips & glutes",
      "Groin",
      "Lower back"
    ]
  },
  {
    "slug": "salamba-bhujangasana",
    "english": "Sphinx Pose",
    "sanskrit": "Salamba Bhujangasana",
    "category": "Backbends",
    "level": "Beginner",
    "holdSeconds": 60,
    "benefits": [
      "Gently strengthens the lower back",
      "Opens the chest and throat",
      "A safe starting point for deeper backbends"
    ],
    "contraindications": [
      "Acute lower-back flare (keep very low)",
      "Wrist-free and elbow-friendly — still ease off if painful"
    ],
    "stretchZones": [
      "Lower back",
      "Chest & throat",
      "Shoulders"
    ]
  },
  {
    "slug": "skandasana",
    "english": "Side Lunge",
    "sanskrit": "Skandasana",
    "category": "Hip Openers",
    "level": "Intermediate",
    "holdSeconds": 30,
    "benefits": [
      "Opens adductors and hips",
      "Strengthens quads and glutes",
      "Builds mobility for squats and wide-legged poses"
    ],
    "contraindications": [
      "Knee injury",
      "Groin strain",
      "Ankle instability"
    ],
    "stretchZones": [
      "Inner thighs",
      "Hips",
      "Ankles"
    ]
  },
  {
    "slug": "makarasana",
    "english": "Crocodile Pose",
    "sanskrit": "Makarasana",
    "category": "Restorative",
    "level": "Beginner",
    "holdSeconds": 90,
    "benefits": [
      "Releases lower-back and sacral tension",
      "Encourages natural diaphragmatic breath",
      "A quiet alternative to Savasana for some bodies"
    ],
    "contraindications": [
      "Pregnancy (skip prone poses)",
      "Recent abdominal surgery",
      "Difficulty lying on the belly"
    ],
    "stretchZones": [
      "Lower back",
      "Belly",
      "Whole body"
    ]
  },
  {
    "slug": "vajrasana",
    "english": "Thunderbolt Pose",
    "sanskrit": "Vajrasana",
    "category": "Seated",
    "level": "Beginner",
    "holdSeconds": 90,
    "benefits": [
      "Aids digestion when practiced after eating",
      "A steady meditation seat for many bodies",
      "Stretches the ankles and tops of the feet"
    ],
    "contraindications": [
      "Knee injury (sit on a block between the heels)",
      "Ankle injury",
      "Recent foot surgery"
    ],
    "stretchZones": [
      "Ankles & feet",
      "Knees",
      "Spine"
    ]
  },
  {
    "slug": "ardha-uttanasana",
    "english": "Halfway Lift",
    "sanskrit": "Ardha Uttanasana",
    "category": "Standing",
    "level": "Beginner",
    "holdSeconds": 20,
    "benefits": [
      "Lengthens the spine and hamstrings",
      "Strengthens the back body",
      "Teaches hinge mechanics for safer forward folds"
    ],
    "contraindications": [
      "Acute lower-back flare (keep knees soft and hands high)",
      "Vertigo (gaze at the floor)"
    ],
    "stretchZones": [
      "Hamstrings",
      "Spine",
      "Back body"
    ]
  },
  {
    "slug": "padahastasana",
    "english": "Hands-to-Feet Pose",
    "sanskrit": "Padahastasana",
    "category": "Forward Bends",
    "level": "Intermediate",
    "holdSeconds": 45,
    "benefits": [
      "Deeply stretches hamstrings and calves",
      "Tractions the spine and releases the neck",
      "Calms the mind in a folded shape"
    ],
    "contraindications": [
      "Hamstring tear",
      "Lower-back disc injury (fold less)",
      "High blood pressure (keep the head elevated)"
    ],
    "stretchZones": [
      "Hamstrings",
      "Spine & neck",
      "Calves"
    ]
  },
  {
    "slug": "utthita-hasta-padangusthasana",
    "english": "Extended Hand-to-Big-Toe",
    "sanskrit": "Utthita Hasta Padangusthasana",
    "category": "Standing",
    "level": "Intermediate",
    "holdSeconds": 30,
    "benefits": [
      "Improves balance and concentration",
      "Stretches hamstrings and hips",
      "Strengthens the standing leg and ankle"
    ],
    "contraindications": [
      "Ankle instability",
      "Hamstring injury",
      "Vertigo or inner-ear issues"
    ],
    "stretchZones": [
      "Standing ankle & leg",
      "Hamstrings",
      "Core"
    ]
  },
  {
    "slug": "parivrtta-parsvakonasana",
    "english": "Revolved Side Angle",
    "sanskrit": "Parivrtta Parsvakonasana",
    "category": "Standing",
    "level": "Intermediate",
    "holdSeconds": 30,
    "benefits": [
      "Strengthens legs and core",
      "Opens the chest and spine in rotation",
      "Builds stamina for longer flows"
    ],
    "contraindications": [
      "Knee injury",
      "Recent spinal injury",
      "Late pregnancy"
    ],
    "stretchZones": [
      "Legs",
      "Spine",
      "Chest"
    ]
  },
  {
    "slug": "chakravakasana",
    "english": "Bird Dog Pose",
    "sanskrit": "Chakravakasana",
    "category": "Restorative",
    "level": "Beginner",
    "holdSeconds": 25,
    "benefits": [
      "Strengthens deep core and back",
      "Improves balance and coordination",
      "Warms the spine without strain"
    ],
    "contraindications": [
      "Wrist pain (practice on fists or forearms)",
      "Knee sensitivity (pad the knees)"
    ],
    "stretchZones": [
      "Core",
      "Back body",
      "Shoulders"
    ]
  },
  {
    "slug": "parivrtta-janu-sirsasana",
    "english": "Revolved Head-to-Knee",
    "sanskrit": "Parivrtta Janu Sirsasana",
    "category": "Seated",
    "level": "Intermediate",
    "holdSeconds": 45,
    "benefits": [
      "Stretches hamstrings and side body",
      "Opens the shoulders and ribs",
      "Improves digestion and spinal mobility"
    ],
    "contraindications": [
      "Hamstring tear",
      "Shoulder injury (reach less)",
      "Disc issues (keep the fold mild)"
    ],
    "stretchZones": [
      "Side body",
      "Hamstrings",
      "Shoulders"
    ]
  },
  {
    "slug": "kurmasana",
    "english": "Tortoise Pose",
    "sanskrit": "Kurmasana",
    "category": "Forward Bends",
    "level": "Advanced",
    "holdSeconds": 40,
    "benefits": [
      "Deeply stretches hamstrings and back",
      "Quiets the nervous system",
      "Opens the shoulders and outer hips"
    ],
    "contraindications": [
      "Hamstring injury",
      "Lower-back injury",
      "Shoulder injury",
      "Pregnancy"
    ],
    "stretchZones": [
      "Hamstrings",
      "Spine",
      "Shoulders"
    ]
  },
  {
    "slug": "bhekasana",
    "english": "Reclining Frog Pose",
    "sanskrit": "Bhekasana",
    "category": "Hip Openers",
    "level": "Intermediate",
    "holdSeconds": 30,
    "benefits": [
      "Stretches quadriceps and hip flexors deeply",
      "Opens the chest and shoulders",
      "Counters long sitting and cycling"
    ],
    "contraindications": [
      "Knee injury",
      "Ankle injury",
      "Lower-back flare (lift the chest less)"
    ],
    "stretchZones": [
      "Quadriceps",
      "Hip flexors",
      "Chest"
    ]
  },
  {
    "slug": "karna-pidasana",
    "english": "Ear Pressure Pose",
    "sanskrit": "Karna Pidasana",
    "category": "Inversions",
    "level": "Intermediate",
    "holdSeconds": 30,
    "benefits": [
      "Deeply stretches the spine and back body",
      "Calms the mind by limiting sensory input",
      "Releases the neck and shoulders gently when supported"
    ],
    "contraindications": [
      "Neck injury",
      "Glaucoma",
      "High blood pressure",
      "Menstruation",
      "Pregnancy"
    ],
    "stretchZones": [
      "Spine",
      "Shoulders",
      "Back body"
    ]
  },
  {
    "slug": "pincha-mayurasana",
    "english": "Forearm Stand",
    "sanskrit": "Pincha Mayurasana",
    "category": "Inversions",
    "level": "Advanced",
    "holdSeconds": 20,
    "benefits": [
      "Builds serious shoulder and core strength",
      "Improves balance and body awareness upside down",
      "Energizes and boosts confidence"
    ],
    "contraindications": [
      "Shoulder or elbow injury",
      "Neck injury",
      "Glaucoma",
      "High blood pressure",
      "Menstruation",
      "Pregnancy"
    ],
    "stretchZones": [
      "Shoulders & upper arms",
      "Core",
      "Wrists & elbows"
    ]
  },
  {
    "slug": "shashankasana",
    "english": "Hare Pose",
    "sanskrit": "Shashankasana",
    "category": "Restorative",
    "level": "Beginner",
    "holdSeconds": 60,
    "benefits": [
      "Calms anxiety and mental chatter",
      "Gently stretches the spine and shoulders",
      "A simple reset between stronger poses"
    ],
    "contraindications": [
      "Knee injury (pad well or skip)",
      "Vertigo (keep the head elevated on a block)",
      "Late pregnancy (widen the knees)"
    ],
    "stretchZones": [
      "Spine",
      "Shoulders",
      "Nervous system"
    ]
  },
  {
    "slug": "urdhva-hastasana",
    "english": "Upward Salute",
    "sanskrit": "Urdhva Hastasana",
    "category": "Standing",
    "level": "Beginner",
    "holdSeconds": 20,
    "benefits": [
      "Lengthens the side body and spine",
      "Energizes and lifts the mood",
      "Teaches full-body extension from the feet"
    ],
    "contraindications": [
      "Shoulder injury (keep a soft bend in the elbows)",
      "Dizziness (keep the gaze forward)"
    ],
    "stretchZones": [
      "Side body",
      "Shoulders",
      "Spine"
    ]
  },
  {
    "slug": "ashtanga-namaskara",
    "english": "Knees-Chest-Chin",
    "sanskrit": "Ashtanga Namaskara",
    "category": "Standing",
    "level": "Beginner",
    "holdSeconds": 10,
    "benefits": [
      "Builds strength toward Chaturanga safely",
      "Opens the chest and strengthens the arms",
      "Makes sun salutations accessible for every body"
    ],
    "contraindications": [
      "Wrist pain (come down onto fists)",
      "Pregnancy (skip or modify heavily)",
      "Shoulder injury"
    ],
    "stretchZones": [
      "Arms & chest",
      "Core",
      "Wrists"
    ]
  },
  {
    "slug": "parivrtta-utkatasana",
    "english": "Revolved Chair",
    "sanskrit": "Parivrtta Utkatasana",
    "category": "Standing",
    "level": "Intermediate",
    "holdSeconds": 25,
    "benefits": [
      "Builds leg strength and heat",
      "Improves spinal mobility and digestion",
      "Sharpens focus under effort"
    ],
    "contraindications": [
      "Knee injury",
      "Low back injury (twist gently)",
      "Pregnancy"
    ],
    "stretchZones": [
      "Thighs",
      "Spine",
      "Core"
    ]
  },
  {
    "slug": "supta-virasana",
    "english": "Reclining Hero",
    "sanskrit": "Supta Virasana",
    "category": "Restorative",
    "level": "Intermediate",
    "holdSeconds": 90,
    "benefits": [
      "Deeply stretches the quadriceps and hip flexors",
      "Opens the front body for better breathing",
      "Restorative when fully propped"
    ],
    "contraindications": [
      "Knee injury (elevate a lot or skip)",
      "Ankle injury",
      "Lower-back pain without props"
    ],
    "stretchZones": [
      "Quadriceps",
      "Hip flexors",
      "Chest"
    ]
  },
  {
    "slug": "anantasana",
    "english": "Side-Reclining Leg Stretch",
    "sanskrit": "Anantasana",
    "category": "Hip Openers",
    "level": "Intermediate",
    "holdSeconds": 30,
    "benefits": [
      "Stretches the hamstrings and inner thighs",
      "Opens the side body",
      "Improves balance in a supported shape"
    ],
    "contraindications": [
      "Hamstring tear",
      "Shoulder injury on the bottom side",
      "Neck discomfort (use a pillow)"
    ],
    "stretchZones": [
      "Hamstrings",
      "Side body",
      "Inner thigh"
    ]
  },
  {
    "slug": "krounchasana",
    "english": "Heron Pose",
    "sanskrit": "Krounchasana",
    "category": "Seated",
    "level": "Intermediate",
    "holdSeconds": 30,
    "benefits": [
      "Deeply stretches the hamstrings",
      "Strengthens the core while seated",
      "Improves focus through balance in a seat"
    ],
    "contraindications": [
      "Knee injury on the folded leg",
      "Hamstring tear",
      "Lower-back disc issues"
    ],
    "stretchZones": [
      "Hamstrings",
      "Core",
      "Folded knee"
    ]
  },
  {
    "slug": "simhasana",
    "english": "Lion Pose",
    "sanskrit": "Simhasana",
    "category": "Seated",
    "level": "Beginner",
    "holdSeconds": 30,
    "benefits": [
      "Releases jaw, face, and throat tension",
      "Relieves stress and self-consciousness",
      "Stimulates the platysma and facial muscles"
    ],
    "contraindications": [
      "Recent facial or dental surgery",
      "Severe neck injury (keep the head neutral)"
    ],
    "stretchZones": [
      "Jaw & face",
      "Throat",
      "Hands & wrists"
    ]
  },
  {
    "slug": "samakonasana",
    "english": "Middle Splits",
    "sanskrit": "Samakonasana",
    "category": "Hip Openers",
    "level": "Advanced",
    "holdSeconds": 45,
    "benefits": [
      "Opens the adductors and hips deeply",
      "Builds the foundation for wide-legged poses",
      "Teaches patience and body honesty"
    ],
    "contraindications": [
      "Groin strain",
      "Hip injury",
      "SI joint instability"
    ],
    "stretchZones": [
      "Inner thighs",
      "Hips",
      "Groin"
    ]
  },
  {
    "slug": "adho-mukha-vrksasana",
    "english": "Handstand",
    "sanskrit": "Adho Mukha Vrksasana",
    "category": "Inversions",
    "level": "Advanced",
    "holdSeconds": 15,
    "benefits": [
      "Builds upper-body and core strength",
      "Improves balance and spatial awareness",
      "Boosts confidence and mental clarity"
    ],
    "contraindications": [
      "Wrist, shoulder, or neck injury",
      "Glaucoma",
      "High blood pressure",
      "Menstruation",
      "Pregnancy"
    ],
    "stretchZones": [
      "Shoulders & arms",
      "Core",
      "Wrists"
    ]
  },
  {
    "slug": "pasasana",
    "english": "Noose Pose",
    "sanskrit": "Pasasana",
    "category": "Hip Openers",
    "level": "Advanced",
    "holdSeconds": 25,
    "benefits": [
      "Deep spinal twist with hip opening",
      "Strengthens ankles and lower legs",
      "Intense digestive stimulation"
    ],
    "contraindications": [
      "Knee or ankle injury",
      "Lower-back injury",
      "Pregnancy"
    ],
    "stretchZones": [
      "Spine",
      "Hips & ankles",
      "Shoulders"
    ]
  },
  {
    "slug": "constructive-rest",
    "english": "Constructive Rest",
    "sanskrit": "Savasana (Constructive Rest)",
    "category": "Restorative",
    "level": "Beginner",
    "holdSeconds": 180,
    "benefits": [
      "Releases the lower back without strain",
      "Downshifts the nervous system for sleep",
      "A safe rest when full Savasana feels too open"
    ],
    "contraindications": [
      "Late pregnancy (widen the knees or lie on the side)",
      "Knee discomfort (place a pillow under the thighs)"
    ],
    "stretchZones": [
      "Lower back",
      "Whole body",
      "Nervous system"
    ]
  },
  {
    "slug": "pawanmuktasana",
    "english": "Wind-Relieving Pose",
    "sanskrit": "Pawanmuktasana",
    "category": "Restorative",
    "level": "Beginner",
    "holdSeconds": 60,
    "benefits": [
      "Relieves gas and digestive discomfort",
      "Softens the lower back",
      "Settles the body before sleep"
    ],
    "contraindications": [
      "Recent abdominal surgery",
      "Late pregnancy (practice one knee at a time)",
      "Hernia"
    ],
    "stretchZones": [
      "Lower back",
      "Belly",
      "Hips"
    ]
  },
  {
    "slug": "chair-viparita-karani",
    "english": "Legs on a Chair",
    "sanskrit": "Viparita Karani (Chair)",
    "category": "Restorative",
    "level": "Beginner",
    "holdSeconds": 240,
    "benefits": [
      "Drains tired legs without a wall",
      "Calms the nervous system deeply",
      "Easier than full Legs-Up for tight hamstrings"
    ],
    "contraindications": [
      "Glaucoma (keep the head elevated)",
      "Serious neck injury",
      "Late pregnancy (lie on the side instead)"
    ],
    "stretchZones": [
      "Legs",
      "Lower back",
      "Nervous system"
    ]
  },
  {
    "slug": "salamba-matsyasana",
    "english": "Supported Fish",
    "sanskrit": "Salamba Matsyasana",
    "category": "Restorative",
    "level": "Beginner",
    "holdSeconds": 120,
    "benefits": [
      "Opens the chest after screen time",
      "Softens the throat and jaw",
      "A restorative heart-opener before bed"
    ],
    "contraindications": [
      "Serious neck injury",
      "Migraine (keep the head supported)",
      "Recent rib injury"
    ],
    "stretchZones": [
      "Chest & throat",
      "Shoulders",
      "Jaw"
    ]
  },
  {
    "slug": "parsva-savasana",
    "english": "Side-Lying Rest",
    "sanskrit": "Parsva Savasana",
    "category": "Restorative",
    "level": "Beginner",
    "holdSeconds": 180,
    "benefits": [
      "Ideal before-bed rest for pregnancy",
      "Supports the spine comfortably",
      "Transitions easily into actual sleep"
    ],
    "contraindications": [
      "Shoulder injury on the bottom side (switch sides)",
      "Difficulty lying on the side"
    ],
    "stretchZones": [
      "Whole body",
      "Hips",
      "Spine"
    ]
  },
  {
    "slug": "salamba-balasana",
    "english": "Supported Child's Pose",
    "sanskrit": "Salamba Balasana",
    "category": "Restorative",
    "level": "Beginner",
    "holdSeconds": 120,
    "benefits": [
      "Deeply calming for anxiety before bed",
      "Releases the back and hips",
      "A propped rest when the floor feels too hard"
    ],
    "contraindications": [
      "Knee injury (sit on a chair and fold forward onto a table)",
      "Late pregnancy (widen the knees a lot)"
    ],
    "stretchZones": [
      "Back body",
      "Hips",
      "Nervous system"
    ]
  },
  {
    "slug": "supta-gomukhasana",
    "english": "Reclined Cow Face",
    "sanskrit": "Supta Gomukhasana",
    "category": "Hip Openers",
    "level": "Beginner",
    "holdSeconds": 60,
    "benefits": [
      "Releases outer hips and glutes",
      "Eases sciatic-friendly tension for many bodies",
      "Quieter than seated Cow Face"
    ],
    "contraindications": [
      "Knee injury (place a blanket between the knees)",
      "Hip replacement (consult your provider)"
    ],
    "stretchZones": [
      "Outer hips",
      "Glutes",
      "Lower back"
    ]
  },
  {
    "slug": "supta-garudasana",
    "english": "Reclined Eagle",
    "sanskrit": "Supta Garudasana",
    "category": "Hip Openers",
    "level": "Beginner",
    "holdSeconds": 45,
    "benefits": [
      "Opens the outer hips and IT band",
      "Gentle compression that feels containing",
      "A calming alternative to figure-four"
    ],
    "contraindications": [
      "Knee injury",
      "Hip bursitis (ease off)"
    ],
    "stretchZones": [
      "Outer hip & IT band",
      "Glutes",
      "Lower back"
    ]
  },
  {
    "slug": "dandasana",
    "english": "Staff Pose",
    "sanskrit": "Dandasana",
    "category": "Seated",
    "level": "Beginner",
    "holdSeconds": 45,
    "benefits": [
      "Teaches upright seated posture",
      "Strengthens the back and core",
      "Prepares the body for folds and twists"
    ],
    "contraindications": [
      "Tight hamstrings (sit on a blanket)",
      "Lower-back flare (bend the knees)"
    ],
    "stretchZones": [
      "Spine",
      "Hamstrings",
      "Core"
    ]
  },
  {
    "slug": "mayurasana",
    "english": "Peacock Pose",
    "sanskrit": "Mayurasana",
    "category": "Standing",
    "level": "Advanced",
    "holdSeconds": 15,
    "benefits": [
      "Builds exceptional arm and core strength",
      "Stimulates digestion",
      "Trains focus and courage"
    ],
    "contraindications": [
      "Wrist or elbow injury",
      "Pregnancy",
      "High blood pressure",
      "Recent abdominal surgery"
    ],
    "stretchZones": [
      "Arms & wrists",
      "Core",
      "Shoulders"
    ]
  },
  {
    "slug": "rajakapotasana",
    "english": "King Pigeon Pose",
    "sanskrit": "Rajakapotasana",
    "category": "Backbends",
    "level": "Advanced",
    "holdSeconds": 18,
    "benefits": [
      "Deeply opens hip flexors, quads, and the chest",
      "Builds spinal flexibility and shoulder mobility",
      "Cultivates courage and emotional release"
    ],
    "contraindications": [
      "Knee, hip, or shoulder injury",
      "Lower-back issues or recent spinal surgery",
      "High or low blood pressure",
      "Pregnancy"
    ],
    "stretchZones": [
      "Hip flexors & quads",
      "Shoulders & chest",
      "Spine"
    ]
  },
  {
    "slug": "astavakrasana",
    "english": "Eight-Angle Pose",
    "sanskrit": "Astavakrasana",
    "category": "Standing",
    "level": "Advanced",
    "holdSeconds": 12,
    "benefits": [
      "Builds significant arm, wrist, and core strength",
      "Improves twisting range through the torso",
      "Trains focus under a demanding shape"
    ],
    "contraindications": [
      "Wrist, elbow, or shoulder injury",
      "Pregnancy",
      "Recent abdominal surgery"
    ],
    "stretchZones": [
      "Wrists & forearms",
      "Obliques & core",
      "Shoulders"
    ]
  },
  {
    "slug": "tittibhasana",
    "english": "Firefly Pose",
    "sanskrit": "Tittibhasana",
    "category": "Standing",
    "level": "Advanced",
    "holdSeconds": 12,
    "benefits": [
      "Builds arm, shoulder, and core strength",
      "Stretches the hamstrings and inner groins",
      "Develops balance and body awareness"
    ],
    "contraindications": [
      "Wrist or shoulder injury",
      "Tight hamstrings — build up gradually",
      "Pregnancy"
    ],
    "stretchZones": [
      "Hamstrings & inner groin",
      "Shoulders & wrists",
      "Core"
    ]
  },
  {
    "slug": "parsva-bakasana",
    "english": "Side Crow Pose",
    "sanskrit": "Parsva Bakasana",
    "category": "Standing",
    "level": "Advanced",
    "holdSeconds": 12,
    "benefits": [
      "Builds arm and wrist strength",
      "Deepens spinal rotation",
      "Sharpens balance and focus"
    ],
    "contraindications": [
      "Wrist injury",
      "Pregnancy",
      "Recent abdominal surgery"
    ],
    "stretchZones": [
      "Spine & obliques",
      "Wrists & forearms",
      "Core"
    ]
  },
  {
    "slug": "eka-pada-koundinyasana-ii",
    "english": "Flying Pigeon Pose",
    "sanskrit": "Eka Pada Koundinyasana II",
    "category": "Standing",
    "level": "Advanced",
    "holdSeconds": 10,
    "benefits": [
      "Builds significant arm and shoulder strength",
      "Opens the front hip while strengthening the back leg",
      "Trains focus and playful courage"
    ],
    "contraindications": [
      "Wrist or shoulder injury",
      "Hip injury",
      "Pregnancy"
    ],
    "stretchZones": [
      "Front hip & groin",
      "Shoulders & wrists",
      "Core & back leg"
    ]
  },
  {
    "slug": "vrischikasana",
    "english": "Scorpion Pose",
    "sanskrit": "Vrischikasana",
    "category": "Inversions",
    "level": "Advanced",
    "holdSeconds": 12,
    "benefits": [
      "Builds exceptional shoulder, core, and back strength",
      "Deepens spinal flexibility",
      "Trains courage, patience, and body trust"
    ],
    "contraindications": [
      "Neck, shoulder, or spinal injury",
      "High or low blood pressure",
      "Pregnancy",
      "Beginners to inversions — build forearm stand first"
    ],
    "stretchZones": [
      "Shoulders & upper back",
      "Spine",
      "Core"
    ]
  },
  {
    "slug": "parivrtta-ardha-chandrasana",
    "english": "Revolved Half Moon Pose",
    "sanskrit": "Parivrtta Ardha Chandrasana",
    "category": "Standing",
    "level": "Advanced",
    "holdSeconds": 25,
    "benefits": [
      "Builds standing-leg strength and balance",
      "Deepens spinal rotation",
      "Sharpens focus and coordination"
    ],
    "contraindications": [
      "Balance difficulty — practice at a wall",
      "Low back injury",
      "High or low blood pressure"
    ],
    "stretchZones": [
      "Spine",
      "Standing leg & hip",
      "Hamstrings (lifted leg)"
    ]
  },
  {
    "slug": "padangusthasana",
    "english": "Big Toe Pose",
    "sanskrit": "Padangusthasana",
    "category": "Forward Bends",
    "level": "Beginner",
    "holdSeconds": 35,
    "benefits": [
      "Lengthens the hamstrings and calves",
      "Improves posture and spinal length",
      "Calms the nervous system"
    ],
    "contraindications": [
      "Low-back injury — bend the knees generously",
      "Sciatica",
      "Low blood pressure — rise slowly"
    ],
    "stretchZones": [
      "Hamstrings",
      "Calves",
      "Spine"
    ]
  },
  {
    "slug": "ardha-baddha-padmottanasana",
    "english": "Half Bound Lotus Forward Bend",
    "sanskrit": "Ardha Baddha Padmottanasana",
    "category": "Standing",
    "level": "Intermediate",
    "holdSeconds": 25,
    "benefits": [
      "Opens the hips and improves balance",
      "Deepens the standing-leg hamstring stretch",
      "Builds focus through a demanding shape"
    ],
    "contraindications": [
      "Knee or hip injury — do not force the half-lotus",
      "Ankle injury",
      "Balance difficulty — practice at a wall"
    ],
    "stretchZones": [
      "Bound hip & knee",
      "Standing-leg hamstring",
      "Ankle (bound foot)"
    ]
  },
  {
    "slug": "high-lunge",
    "english": "High Lunge",
    "sanskrit": "Utthita Ashwa Sanchalanasana",
    "category": "Standing",
    "level": "Beginner",
    "holdSeconds": 25,
    "benefits": [
      "Strengthens the legs and core",
      "Opens the hip flexors of the back leg",
      "Builds heat and stability for standing flows"
    ],
    "contraindications": [
      "Knee injury — shorten the stance",
      "High blood pressure — keep arms lower if lightheaded",
      "Balance difficulty"
    ],
    "stretchZones": [
      "Back-leg hip flexor",
      "Front thigh & glute",
      "Core"
    ]
  },
  {
    "slug": "baddha-virabhadrasana",
    "english": "Humble Warrior",
    "sanskrit": "Baddha Virabhadrasana",
    "category": "Standing",
    "level": "Beginner",
    "holdSeconds": 25,
    "benefits": [
      "Opens the shoulders and chest",
      "Builds strong legs and hips",
      "Quiets the mind while staying strong"
    ],
    "contraindications": [
      "Knee injury — shorten the stance",
      "Neck issues — keep the gaze soft and neck long",
      "Low blood pressure — rise slowly"
    ],
    "stretchZones": [
      "Front thigh & hip",
      "Shoulders & chest",
      "Hamstrings"
    ]
  },
  {
    "slug": "baddha-parsvakonasana",
    "english": "Bound Side Angle",
    "sanskrit": "Baddha Parsvakonasana",
    "category": "Standing",
    "level": "Intermediate",
    "holdSeconds": 25,
    "benefits": [
      "Opens the hips, shoulders, and chest",
      "Strengthens the legs",
      "Improves balance and focus"
    ],
    "contraindications": [
      "Shoulder injury — skip the bind",
      "Knee issues — shorten the stance",
      "Pregnancy — avoid deep compression"
    ],
    "stretchZones": [
      "Front hip & groin",
      "Shoulders & chest",
      "Back leg"
    ]
  },
  {
    "slug": "parivrtta-hasta-padangusthasana",
    "english": "Revolved Hand-to-Big-Toe Pose",
    "sanskrit": "Parivrtta Hasta Padangusthasana",
    "category": "Standing",
    "level": "Intermediate",
    "holdSeconds": 20,
    "benefits": [
      "Builds balance and concentration",
      "Stretches the hamstrings",
      "Strengthens the standing leg and core"
    ],
    "contraindications": [
      "Hamstring injury",
      "Balance disorders — practice near a wall",
      "Low back disc issues — keep the twist gentle"
    ],
    "stretchZones": [
      "Standing-leg hamstring & hip",
      "Lifted-leg hamstring",
      "Core & waist"
    ]
  },
  {
    "slug": "parivrtta-paschimottanasana",
    "english": "Revolved Seated Forward Bend",
    "sanskrit": "Parivrtta Paschimottanasana",
    "category": "Forward Bends",
    "level": "Intermediate",
    "holdSeconds": 35,
    "benefits": [
      "Stretches the hamstrings and spine",
      "Stimulates digestion",
      "Releases mid-back tension"
    ],
    "contraindications": [
      "Acute low-back pain",
      "Hamstring tear",
      "Pregnancy — skip deep twists"
    ],
    "stretchZones": [
      "Hamstrings",
      "Spine & waist",
      "Outer hip (crossed leg)"
    ]
  },
  {
    "slug": "jathara-parivartanasana",
    "english": "Revolved Abdomen Pose",
    "sanskrit": "Jathara Parivartanasana",
    "category": "Restorative",
    "level": "Beginner",
    "holdSeconds": 60,
    "benefits": [
      "Releases the lower back",
      "Aids digestion",
      "Calms the mind before rest"
    ],
    "contraindications": [
      "Recent abdominal surgery",
      "Disc herniation — keep knees stacked and twist small",
      "Pregnancy — use a propped open twist instead"
    ],
    "stretchZones": [
      "Lower back",
      "Waist & belly",
      "Chest & shoulders"
    ]
  },
  {
    "slug": "uttana-padasana",
    "english": "Raised Legs Pose",
    "sanskrit": "Uttana Padasana",
    "category": "Seated",
    "level": "Intermediate",
    "holdSeconds": 30,
    "benefits": [
      "Strengthens the deep core",
      "Stabilizes the low back",
      "Builds heat without jumping"
    ],
    "contraindications": [
      "Acute low-back pain",
      "Hernia",
      "Pregnancy",
      "Neck injury — support the head"
    ],
    "stretchZones": [
      "Core",
      "Hip flexors",
      "Low back"
    ]
  },
  {
    "slug": "tolasana",
    "english": "Scale Pose",
    "sanskrit": "Tolasana",
    "category": "Seated",
    "level": "Intermediate",
    "holdSeconds": 15,
    "benefits": [
      "Strengthens wrists, arms, and core",
      "Builds lift for arm balances",
      "Sharpens focus"
    ],
    "contraindications": [
      "Wrist injury",
      "Knee issues in full Lotus — use Easy Seat instead",
      "Shoulder instability"
    ],
    "stretchZones": [
      "Wrists & arms",
      "Core",
      "Hips"
    ]
  },
  {
    "slug": "bhujapidasana",
    "english": "Shoulder-Pressing Pose",
    "sanskrit": "Bhujapidasana",
    "category": "Standing",
    "level": "Advanced",
    "holdSeconds": 15,
    "benefits": [
      "Builds arm, wrist, and core strength",
      "Opens the hips through compression",
      "Trains balance and courage"
    ],
    "contraindications": [
      "Wrist or shoulder injury",
      "Pregnancy",
      "Recent hip surgery"
    ],
    "stretchZones": [
      "Arms & wrists",
      "Core",
      "Inner thighs & hips"
    ]
  },
  {
    "slug": "galavasana",
    "english": "Flying Pigeon Pose",
    "sanskrit": "Galavasana",
    "category": "Hip Openers",
    "level": "Advanced",
    "holdSeconds": 12,
    "benefits": [
      "Deep outer-hip opening",
      "Builds arm and core strength",
      "Combines flexibility with focus"
    ],
    "contraindications": [
      "Wrist injury",
      "Knee pain in the folded leg",
      "Shoulder instability"
    ],
    "stretchZones": [
      "Outer hip (folded leg)",
      "Arms & shoulders",
      "Core"
    ]
  },
  {
    "slug": "eka-pada-bakasana",
    "english": "One-Legged Crow Pose",
    "sanskrit": "Eka Pada Bakasana",
    "category": "Standing",
    "level": "Advanced",
    "holdSeconds": 10,
    "benefits": [
      "Advances Crow practice",
      "Strengthens core and shoulders",
      "Builds single-leg control in arm balances"
    ],
    "contraindications": [
      "Wrist injury",
      "Shoulder instability",
      "Pregnancy"
    ],
    "stretchZones": [
      "Arms & wrists",
      "Core",
      "Shoulders"
    ]
  },
  {
    "slug": "ardha-navasana",
    "english": "Half Boat Pose",
    "sanskrit": "Ardha Navasana",
    "category": "Seated",
    "level": "Intermediate",
    "holdSeconds": 30,
    "benefits": [
      "Strengthens the deep abdominals",
      "Builds endurance for full Boat",
      "Supports posture"
    ],
    "contraindications": [
      "Acute low-back pain",
      "Neck injury — support the head",
      "Pregnancy"
    ],
    "stretchZones": [
      "Core",
      "Hip flexors",
      "Spine"
    ]
  },
  {
    "slug": "marichyasana-a",
    "english": "Marichi's Pose A",
    "sanskrit": "Marichyasana A",
    "category": "Forward Bends",
    "level": "Intermediate",
    "holdSeconds": 35,
    "benefits": [
      "Stretches hamstrings and spine",
      "Improves digestion",
      "Builds shoulder mobility for binds"
    ],
    "contraindications": [
      "Hamstring tear",
      "Shoulder injury — skip the bind",
      "Pregnancy — avoid deep compression"
    ],
    "stretchZones": [
      "Hamstrings",
      "Shoulders",
      "Spine"
    ]
  },
  {
    "slug": "eka-pada-adho-mukha-svanasana",
    "english": "Three-Legged Dog",
    "sanskrit": "Eka Pada Adho Mukha Svanasana",
    "category": "Standing",
    "level": "Beginner",
    "holdSeconds": 20,
    "benefits": [
      "Opens the hip flexors and hamstrings",
      "Strengthens shoulders and arms",
      "Preps lunges and warriors"
    ],
    "contraindications": [
      "Wrist injury",
      "Shoulder instability",
      "High blood pressure — keep the head above the heart if needed"
    ],
    "stretchZones": [
      "Lifted-leg hip",
      "Shoulders & arms",
      "Standing-leg hamstring"
    ]
  },
  {
    "slug": "parsva-uttanasana",
    "english": "Sideways Forward Fold",
    "sanskrit": "Parsva Uttanasana",
    "category": "Forward Bends",
    "level": "Intermediate",
    "holdSeconds": 25,
    "benefits": [
      "Stretches hamstrings and side body",
      "Relieves waist tension",
      "Builds balance in folds"
    ],
    "contraindications": [
      "Hamstring injury",
      "Low-back disc issues — keep a soft bend in the knees",
      "Vertigo — rise slowly"
    ],
    "stretchZones": [
      "Hamstrings",
      "Side waist",
      "Low back"
    ]
  },
  {
    "slug": "salamba-setu-bandhasana",
    "english": "Supported Bridge Pose",
    "sanskrit": "Salamba Setu Bandhasana",
    "category": "Restorative",
    "level": "Beginner",
    "holdSeconds": 120,
    "benefits": [
      "Opens the chest gently",
      "Relieves tired legs and low back",
      "Calms the nervous system"
    ],
    "contraindications": [
      "Acute neck injury",
      "Recent spinal surgery",
      "Pregnancy — use a lower prop or skip"
    ],
    "stretchZones": [
      "Chest",
      "Hip flexors",
      "Low back"
    ]
  },
  {
    "slug": "parivrtta-upavistha-konasana",
    "english": "Revolved Wide-Angle Pose",
    "sanskrit": "Parivrtta Upavistha Konasana",
    "category": "Seated",
    "level": "Intermediate",
    "holdSeconds": 35,
    "benefits": [
      "Opens the hamstrings and inner thighs",
      "Stretches the side waist",
      "Improves seated mobility"
    ],
    "contraindications": [
      "Hamstring tear",
      "Groin injury",
      "Pregnancy — keep the twist mild"
    ],
    "stretchZones": [
      "Inner thighs",
      "Hamstrings",
      "Side waist"
    ]
  },
  {
    "slug": "camatkarasana",
    "english": "Wild Thing",
    "sanskrit": "Camatkarasana",
    "category": "Backbends",
    "level": "Intermediate",
    "holdSeconds": 20,
    "benefits": [
      "Opens the chest and hip flexors",
      "Strengthens the supporting arm and shoulder",
      "Invites joy into practice"
    ],
    "contraindications": [
      "Wrist or shoulder injury",
      "Acute low-back pain",
      "Pregnancy"
    ],
    "stretchZones": [
      "Chest & shoulders",
      "Supporting arm",
      "Hip flexors"
    ]
  },
  {
    "slug": "makara-adho-mukha-svanasana",
    "english": "Dolphin Pose",
    "sanskrit": "Makara Adho Mukha Svanasana",
    "category": "Inversions",
    "level": "Intermediate",
    "holdSeconds": 30,
    "benefits": [
      "Strengthens shoulders and core",
      "Stretches hamstrings and calves",
      "Prepares for Forearm Stand"
    ],
    "contraindications": [
      "Shoulder injury",
      "Neck issues — keep the head off the floor",
      "High blood pressure — come down if dizzy"
    ],
    "stretchZones": [
      "Shoulders",
      "Hamstrings",
      "Core"
    ]
  },
  {
    "slug": "standing-figure-four",
    "english": "Standing Figure-Four",
    "sanskrit": "Eka Pada Utkatasana Prep",
    "category": "Standing",
    "level": "Beginner",
    "holdSeconds": 25,
    "benefits": [
      "Opens the outer hip",
      "Builds single-leg strength",
      "Counters long sitting"
    ],
    "contraindications": [
      "Knee pain — keep the figure-four gentle",
      "Balance difficulty — use a wall",
      "Ankle injury"
    ],
    "stretchZones": [
      "Hips",
      "Thighs",
      "Core"
    ]
  },
  {
    "slug": "runner-lunge-twist",
    "english": "Runner's Lunge Twist",
    "sanskrit": "Parivrtta Anjaneyasana Athletic",
    "category": "Standing",
    "level": "Intermediate",
    "holdSeconds": 25,
    "benefits": [
      "Opens hip flexors",
      "Mobilizes the thoracic spine",
      "Builds leg strength"
    ],
    "contraindications": [
      "Knee injury — shorten the stance",
      "Low-back disc issues — keep the twist mild",
      "Pregnancy — skip deep twists"
    ],
    "stretchZones": [
      "Spine",
      "Hips",
      "Shoulders"
    ]
  },
  {
    "slug": "dolphin-plank",
    "english": "Dolphin Plank",
    "sanskrit": "Makara Phalakasana",
    "category": "Standing",
    "level": "Intermediate",
    "holdSeconds": 30,
    "benefits": [
      "Strengthens shoulders and core",
      "Wrist-friendly plank option",
      "Builds endurance for inversions"
    ],
    "contraindications": [
      "Shoulder injury",
      "Low-back pain — lift the hips slightly",
      "Pregnancy — modify on knees"
    ],
    "stretchZones": [
      "Core",
      "Shoulders",
      "Legs"
    ]
  },
  {
    "slug": "reverse-tabletop",
    "english": "Reverse Tabletop",
    "sanskrit": "Ardha Purvottanasana",
    "category": "Seated",
    "level": "Beginner",
    "holdSeconds": 25,
    "benefits": [
      "Opens the chest and shoulders",
      "Strengthens arms and glutes",
      "Counters desk posture"
    ],
    "contraindications": [
      "Wrist injury — turn fingers sideways",
      "Neck issues — keep the head neutral",
      "Shoulder instability"
    ],
    "stretchZones": [
      "Chest",
      "Shoulders",
      "Arms"
    ]
  },
  {
    "slug": "couch-hip-flexor",
    "english": "Couch Hip-Flexor Stretch",
    "sanskrit": "Utthan Pristhasana Couch",
    "category": "Hip Openers",
    "level": "Beginner",
    "holdSeconds": 60,
    "benefits": [
      "Opens tight hip flexors",
      "Supports athletic recovery",
      "Improves standing posture"
    ],
    "contraindications": [
      "Knee injury on the back knee — pad well",
      "Low-back pain — tuck the pelvis",
      "Recent hip surgery"
    ],
    "stretchZones": [
      "Hips",
      "Thighs",
      "Core"
    ]
  },
  {
    "slug": "standing-side-stretch",
    "english": "Standing Side Stretch",
    "sanskrit": "Parsva Urdhva Hastasana",
    "category": "Standing",
    "level": "Beginner",
    "holdSeconds": 25,
    "benefits": [
      "Opens the side body",
      "Improves lateral mobility",
      "Feels great after desk work"
    ],
    "contraindications": [
      "Low-back issues — keep the bend small",
      "Shoulder injury — keep arms lower",
      "Vertigo — move slowly"
    ],
    "stretchZones": [
      "Side waist",
      "Ribs",
      "Shoulders"
    ]
  },
  {
    "slug": "twisted-lizard",
    "english": "Twisted Lizard",
    "sanskrit": "Parivrtta Utthan Pristhasana",
    "category": "Hip Openers",
    "level": "Intermediate",
    "holdSeconds": 25,
    "benefits": [
      "Deep hip flexor and groin opening",
      "Thoracic mobility",
      "Athletic flow peak pose"
    ],
    "contraindications": [
      "Knee injury",
      "Hamstring strain",
      "Pregnancy — skip deep compression"
    ],
    "stretchZones": [
      "Hips",
      "Thighs",
      "Core"
    ]
  },
  {
    "slug": "prasarita-c",
    "english": "Bound Wide-Leg Forward Fold",
    "sanskrit": "Prasarita Padottanasana C",
    "category": "Forward Bends",
    "level": "Intermediate",
    "holdSeconds": 35,
    "benefits": [
      "Stretches hamstrings",
      "Opens the shoulders and chest",
      "Calms while building strength"
    ],
    "contraindications": [
      "Hamstring tear",
      "Shoulder injury — skip the clasp",
      "Low blood pressure — rise slowly"
    ],
    "stretchZones": [
      "Hamstrings",
      "Shoulders",
      "Spine"
    ]
  },
  {
    "slug": "kneeling-thoracic-opener",
    "english": "Kneeling Chest Opener",
    "sanskrit": "Thread the Needle Kneeling",
    "category": "Seated",
    "level": "Beginner",
    "holdSeconds": 35,
    "benefits": [
      "Releases upper-back tension",
      "Opens the chest",
      "Improves shoulder mobility"
    ],
    "contraindications": [
      "Knee pain — pad the knees",
      "Shoulder injury — keep the open smaller",
      "Neck issues — gaze soft"
    ],
    "stretchZones": [
      "Upper back",
      "Shoulders",
      "Neck"
    ]
  },
  {
    "slug": "wall-chest-opener",
    "english": "Wall Chest Opener",
    "sanskrit": "Wall Chest Stretch",
    "category": "Standing",
    "level": "Beginner",
    "holdSeconds": 35,
    "benefits": [
      "Opens the chest and biceps",
      "Counters pressing and desk work",
      "Improves posture quickly"
    ],
    "contraindications": [
      "Shoulder injury — keep the elbow lower",
      "Recent surgery",
      "Numbness in the hand — ease off"
    ],
    "stretchZones": [
      "Chest",
      "Shoulders",
      "Arms"
    ]
  },
  {
    "slug": "banana-pose",
    "english": "Banana Pose",
    "sanskrit": "Chandrasana",
    "category": "Restorative",
    "level": "Beginner",
    "holdSeconds": 90,
    "benefits": [
      "Lengthens the side body",
      "Softens the low back",
      "Restorative and pregnancy-friendly with care"
    ],
    "contraindications": [
      "Acute low-back pain",
      "Disc issues — keep the crescent mild",
      "SI joint pain — skip if it aggravates"
    ],
    "stretchZones": [
      "Side waist",
      "Ribs",
      "Shoulders"
    ]
  },
  {
    "slug": "mermaid-pose",
    "english": "Mermaid Pose",
    "sanskrit": "Eka Pada Rajakapotasana Mermaid",
    "category": "Hip Openers",
    "level": "Intermediate",
    "holdSeconds": 35,
    "benefits": [
      "Opens the hips and side body",
      "Stretches the quads",
      "Feels empowering and spacious"
    ],
    "contraindications": [
      "Knee pain in the front leg",
      "Shoulder injury — skip the bind",
      "Pregnancy — keep upright without the bind"
    ],
    "stretchZones": [
      "Hips",
      "Thighs",
      "Core"
    ]
  },
  {
    "slug": "deer-pose",
    "english": "Deer Pose",
    "sanskrit": "Mrigasana",
    "category": "Hip Openers",
    "level": "Beginner",
    "holdSeconds": 75,
    "benefits": [
      "Gently opens the hips",
      "Calms the nervous system",
      "Accessible floor practice"
    ],
    "contraindications": [
      "Knee injury — support with blankets",
      "Ankle pain",
      "SI discomfort — reduce the twist"
    ],
    "stretchZones": [
      "Hips",
      "Thighs",
      "Core"
    ]
  },
  {
    "slug": "caterpillar",
    "english": "Caterpillar Pose",
    "sanskrit": "Paschimottanasana Yin",
    "category": "Forward Bends",
    "level": "Beginner",
    "holdSeconds": 150,
    "benefits": [
      "Releases the spine and hamstrings",
      "Turns the senses inward",
      "Deeply calming"
    ],
    "contraindications": [
      "Disc herniation — sit taller with less round",
      "Hamstring tear",
      "Depression — keep the fold shorter if it feels heavy"
    ],
    "stretchZones": [
      "Spine",
      "Hamstrings",
      "Nervous system"
    ]
  },
  {
    "slug": "dragonfly",
    "english": "Dragonfly Pose",
    "sanskrit": "Upavistha Konasana Yin",
    "category": "Seated",
    "level": "Beginner",
    "holdSeconds": 150,
    "benefits": [
      "Opens the inner thighs",
      "Stretches the hamstrings",
      "Restorative flexibility work"
    ],
    "contraindications": [
      "Groin injury",
      "Hamstring tear",
      "SI joint pain — fold less"
    ],
    "stretchZones": [
      "Inner thighs",
      "Hamstrings",
      "Low back"
    ]
  },
  {
    "slug": "swan-pose",
    "english": "Swan Pose",
    "sanskrit": "Kapotasana Yin Swan",
    "category": "Hip Openers",
    "level": "Beginner",
    "holdSeconds": 90,
    "benefits": [
      "Deep outer-hip release",
      "Emotional settling",
      "Prepares for deeper hip openers"
    ],
    "contraindications": [
      "Knee pain — use Supine Figure-Four instead",
      "SI joint issues",
      "Recent hip surgery"
    ],
    "stretchZones": [
      "Hips",
      "Thighs",
      "Core"
    ]
  },
  {
    "slug": "wall-butterfly",
    "english": "Wall Butterfly",
    "sanskrit": "Supta Baddha Konasana Wall",
    "category": "Restorative",
    "level": "Beginner",
    "holdSeconds": 180,
    "benefits": [
      "Restorative hip opening",
      "Supports hormonal calm",
      "Beautiful before bed"
    ],
    "contraindications": [
      "Knee pain — support thighs with blankets",
      "Low-back discomfort — scoot farther from the wall",
      "Groin strain"
    ],
    "stretchZones": [
      "Hips",
      "Thighs",
      "Core"
    ]
  },
  {
    "slug": "wide-child-pose",
    "english": "Wide-Knee Child's Pose",
    "sanskrit": "Prasarita Balasana",
    "category": "Restorative",
    "level": "Beginner",
    "holdSeconds": 120,
    "benefits": [
      "Calms the nervous system",
      "Gentle hip release",
      "Safe pause anytime"
    ],
    "contraindications": [
      "Knee injury — pad well",
      "Ankle pain",
      "Pregnancy — keep knees wide and belly free"
    ],
    "stretchZones": [
      "Hips",
      "Back body",
      "Mind"
    ]
  },
  {
    "slug": "seated-side-bend",
    "english": "Seated Side Bend",
    "sanskrit": "Parsva Sukhasana",
    "category": "Seated",
    "level": "Beginner",
    "holdSeconds": 35,
    "benefits": [
      "Opens the side waist",
      "Creates space for the breath",
      "Gentle daily mobility"
    ],
    "contraindications": [
      "Shoulder injury — keep the top arm lower",
      "Low-back pain — shorten the bend",
      "Neck issues — gaze forward"
    ],
    "stretchZones": [
      "Side waist",
      "Ribs",
      "Shoulders"
    ]
  },
  {
    "slug": "supported-squat",
    "english": "Supported Squat",
    "sanskrit": "Salamba Malasana",
    "category": "Hip Openers",
    "level": "Beginner",
    "holdSeconds": 60,
    "benefits": [
      "Opens the hips and ankles",
      "Grounding and settling",
      "Supports pelvic mobility"
    ],
    "contraindications": [
      "Knee injury — sit on a block",
      "Ankle stiffness — elevate the heels more",
      "Balance difficulty — hold a stable surface"
    ],
    "stretchZones": [
      "Hips",
      "Thighs",
      "Core"
    ]
  }
];

export const COACH_CATALOG_SLUGS = new Set(COACH_CATALOG.map((p) => p.slug));

// Compact one-line-per-pose JSON string bundled into the system prompt.
export const COACH_CATALOG_JSON = JSON.stringify(
  COACH_CATALOG.map((p) => ({
    slug: p.slug,
    english: p.english,
    sanskrit: p.sanskrit,
    category: p.category,
    level: p.level,
    holdSeconds: p.holdSeconds,
    benefits: p.benefits,
    contraindications: p.contraindications,
    stretchZones: p.stretchZones,
  })),
);
