// AUTO-GENERATED by script/gen-coach-catalog.ts — do not edit by hand.
// Compact pose catalog for the AI Yoga Coach compose endpoint (v4).
export type CoachPose = {
  slug: string;
  english: string;
  sanskrit: string;
  category: string;
  level: string;
  holdSeconds: number;
  benefits: string[];
  contraindications: string[];
  stretchZones: string[];
};

export const COACH_CATALOG: CoachPose[] = [
  {
    "slug": "tadasana",
    "english": "Mountain Pose",
    "sanskrit": "Tadasana",
    "category": "Standing",
    "level": "Beginner",
    "holdSeconds": 45,
    "benefits": [
      "Improves posture and body awareness",
      "Strengthens thighs, knees, and ankles",
      "Calms the mind and steadies the breath"
    ],
    "contraindications": [
      "Low blood pressure (rise slowly)",
      "Dizziness or vertigo"
    ],
    "stretchZones": [
      "Feet",
      "Spine",
      "Shoulders"
    ]
  },
  {
    "slug": "vrksasana",
    "english": "Tree Pose",
    "sanskrit": "Vrksasana",
    "category": "Standing",
    "level": "Beginner",
    "holdSeconds": 30,
    "benefits": [
      "Improves balance and concentration",
      "Strengthens ankles, calves, and core",
      "Opens the hips and chest"
    ],
    "contraindications": [
      "Recent ankle or knee injury",
      "Migraine or severe low blood pressure"
    ],
    "stretchZones": [
      "Standing ankle & calf",
      "Inner thigh",
      "Core"
    ]
  },
  {
    "slug": "virabhadrasana-ii",
    "english": "Warrior II",
    "sanskrit": "Virabhadrasana II",
    "category": "Standing",
    "level": "Beginner",
    "holdSeconds": 40,
    "benefits": [
      "Strengthens legs, glutes, and shoulders",
      "Opens the hips and chest",
      "Builds endurance and concentration"
    ],
    "contraindications": [
      "Knee injury (mind front-knee tracking)",
      "High blood pressure",
      "Diarrhea"
    ],
    "stretchZones": [
      "Front thigh & glute",
      "Inner thighs & groin",
      "Shoulders"
    ]
  },
  {
    "slug": "virabhadrasana-i",
    "english": "Warrior I",
    "sanskrit": "Virabhadrasana I",
    "category": "Standing",
    "level": "Intermediate",
    "holdSeconds": 40,
    "benefits": [
      "Strengthens legs and core",
      "Stretches hip flexors and chest",
      "Improves focus and balance"
    ],
    "contraindications": [
      "High blood pressure",
      "Shoulder issues (keep arms wider)",
      "Heart conditions"
    ],
    "stretchZones": [
      "Back-leg hip flexor",
      "Front thigh",
      "Chest & shoulders"
    ]
  },
  {
    "slug": "trikonasana",
    "english": "Triangle Pose",
    "sanskrit": "Trikonasana",
    "category": "Standing",
    "level": "Beginner",
    "holdSeconds": 40,
    "benefits": [
      "Stretches hamstrings, hips, and side body",
      "Strengthens legs and core",
      "Relieves back stiffness"
    ],
    "contraindications": [
      "Low blood pressure",
      "Neck issues (don't turn head up)",
      "Headache"
    ],
    "stretchZones": [
      "Front hamstring",
      "Side body",
      "Hips"
    ]
  },
  {
    "slug": "utkatasana",
    "english": "Chair Pose",
    "sanskrit": "Utkatasana",
    "category": "Standing",
    "level": "Beginner",
    "holdSeconds": 30,
    "benefits": [
      "Strengthens thighs, glutes, and ankles",
      "Tones the core",
      "Builds heat and stamina"
    ],
    "contraindications": [
      "Knee pain",
      "Low blood pressure",
      "Insomnia"
    ],
    "stretchZones": [
      "Thighs & quads",
      "Glutes",
      "Shoulders"
    ]
  },
  {
    "slug": "ardha-chandrasana",
    "english": "Half Moon Pose",
    "sanskrit": "Ardha Chandrasana",
    "category": "Standing",
    "level": "Intermediate",
    "holdSeconds": 25,
    "benefits": [
      "Strengthens ankles, legs, and core",
      "Improves balance and coordination",
      "Opens chest and hips"
    ],
    "contraindications": [
      "Low blood pressure",
      "Headache or migraine",
      "Neck injury"
    ],
    "stretchZones": [
      "Standing leg & hip",
      "Hamstring",
      "Chest & side body"
    ]
  },
  {
    "slug": "sukhasana",
    "english": "Easy Seat",
    "sanskrit": "Sukhasana",
    "category": "Seated",
    "level": "Beginner",
    "holdSeconds": 60,
    "benefits": [
      "Opens the hips",
      "Lengthens the spine",
      "Calms the nervous system"
    ],
    "contraindications": [
      "Knee injury (sit elevated)",
      "Sciatica"
    ],
    "stretchZones": [
      "Hips & outer hips",
      "Spine",
      "Knees"
    ]
  },
  {
    "slug": "padmasana",
    "english": "Lotus Pose",
    "sanskrit": "Padmasana",
    "category": "Seated",
    "level": "Advanced",
    "holdSeconds": 60,
    "benefits": [
      "Deeply opens hips",
      "Steadies the mind for meditation",
      "Improves posture"
    ],
    "contraindications": [
      "Knee or ankle injury",
      "Tight hips (use Half Lotus or Easy Seat instead)"
    ],
    "stretchZones": [
      "Hips",
      "Knees",
      "Ankles"
    ]
  },
  {
    "slug": "navasana",
    "english": "Boat Pose",
    "sanskrit": "Navasana",
    "category": "Seated",
    "level": "Intermediate",
    "holdSeconds": 25,
    "benefits": [
      "Strengthens the core and hip flexors",
      "Improves balance",
      "Tones the spine"
    ],
    "contraindications": [
      "Low back injury",
      "Pregnancy",
      "Recent abdominal surgery"
    ],
    "stretchZones": [
      "Core & abdominals",
      "Hip flexors",
      "Spine"
    ]
  },
  {
    "slug": "baddha-konasana",
    "english": "Butterfly / Bound Angle",
    "sanskrit": "Baddha Konasana",
    "category": "Hip Openers",
    "level": "Beginner",
    "holdSeconds": 60,
    "benefits": [
      "Opens hips and inner thighs",
      "Stimulates circulation",
      "Soothes the nervous system"
    ],
    "contraindications": [
      "Groin or knee injury",
      "Sciatica (sit elevated)"
    ],
    "stretchZones": [
      "Inner thighs & groin",
      "Hips",
      "Lower back"
    ]
  },
  {
    "slug": "eka-pada-rajakapotasana",
    "english": "Pigeon Pose",
    "sanskrit": "Eka Pada Rajakapotasana",
    "category": "Hip Openers",
    "level": "Intermediate",
    "holdSeconds": 60,
    "benefits": [
      "Opens hip rotators and glutes",
      "Stretches hip flexors of the back leg",
      "Releases low-back tension"
    ],
    "contraindications": [
      "Knee injury",
      "Sacroiliac issues",
      "Tight hips (use a prop)"
    ],
    "stretchZones": [
      "Front-leg outer hip & piriformis",
      "Back-leg hip flexor",
      "Lower back"
    ]
  },
  {
    "slug": "anjaneyasana",
    "english": "Low Lunge",
    "sanskrit": "Anjaneyasana",
    "category": "Hip Openers",
    "level": "Beginner",
    "holdSeconds": 45,
    "benefits": [
      "Stretches hip flexors and quadriceps",
      "Opens the chest",
      "Builds leg stability"
    ],
    "contraindications": [
      "Knee sensitivity (pad the back knee)",
      "High blood pressure (keep hands down)"
    ],
    "stretchZones": [
      "Back-leg hip flexor",
      "Quadriceps",
      "Chest"
    ]
  },
  {
    "slug": "utthan-pristhasana",
    "english": "Lizard Pose",
    "sanskrit": "Utthan Pristhasana",
    "category": "Hip Openers",
    "level": "Intermediate",
    "holdSeconds": 60,
    "benefits": [
      "Deeply opens hips and hip flexors",
      "Stretches hamstrings",
      "Prepares the body for splits"
    ],
    "contraindications": [
      "Knee or hip injury",
      "Recent groin strain"
    ],
    "stretchZones": [
      "Front hip & inner groin",
      "Hamstrings",
      "Back-leg hip flexor"
    ]
  },
  {
    "slug": "uttanasana",
    "english": "Standing Forward Fold",
    "sanskrit": "Uttanasana",
    "category": "Forward Bends",
    "level": "Beginner",
    "holdSeconds": 45,
    "benefits": [
      "Stretches hamstrings and calves",
      "Calms the mind",
      "Relieves tension in the neck and back"
    ],
    "contraindications": [
      "Low back injury (bend knees)",
      "High blood pressure",
      "Glaucoma"
    ],
    "stretchZones": [
      "Hamstrings",
      "Calves",
      "Neck & back"
    ]
  },
  {
    "slug": "paschimottanasana",
    "english": "Seated Forward Bend",
    "sanskrit": "Paschimottanasana",
    "category": "Forward Bends",
    "level": "Beginner",
    "holdSeconds": 60,
    "benefits": [
      "Stretches the entire back body",
      "Calms the nervous system",
      "Aids digestion"
    ],
    "contraindications": [
      "Low back injury",
      "Sciatica (sit elevated, bend knees)",
      "Asthma"
    ],
    "stretchZones": [
      "Hamstrings",
      "Lower back",
      "Calves"
    ]
  },
  {
    "slug": "parsvottanasana",
    "english": "Pyramid Pose",
    "sanskrit": "Parsvottanasana",
    "category": "Forward Bends",
    "level": "Intermediate",
    "holdSeconds": 40,
    "benefits": [
      "Deeply stretches hamstrings",
      "Improves balance",
      "Strengthens legs"
    ],
    "contraindications": [
      "High blood pressure",
      "Low back injury",
      "Hamstring tear"
    ],
    "stretchZones": [
      "Front-leg hamstring",
      "Hips",
      "Spine"
    ]
  },
  {
    "slug": "bhujangasana",
    "english": "Cobra Pose",
    "sanskrit": "Bhujangasana",
    "category": "Backbends",
    "level": "Beginner",
    "holdSeconds": 25,
    "benefits": [
      "Strengthens the spine",
      "Opens chest and shoulders",
      "Soothes sciatica"
    ],
    "contraindications": [
      "Back injury",
      "Pregnancy",
      "Carpal tunnel syndrome"
    ],
    "stretchZones": [
      "Spine & back",
      "Chest",
      "Abdominals"
    ]
  },
  {
    "slug": "setu-bandhasana",
    "english": "Bridge Pose",
    "sanskrit": "Setu Bandha Sarvangasana",
    "category": "Backbends",
    "level": "Beginner",
    "holdSeconds": 45,
    "benefits": [
      "Strengthens back, glutes, and hamstrings",
      "Opens the chest",
      "Calms the mind"
    ],
    "contraindications": [
      "Neck injury",
      "Shoulder issues"
    ],
    "stretchZones": [
      "Chest",
      "Hip flexors",
      "Back & glutes"
    ]
  },
  {
    "slug": "ustrasana",
    "english": "Camel Pose",
    "sanskrit": "Ustrasana",
    "category": "Backbends",
    "level": "Intermediate",
    "holdSeconds": 25,
    "benefits": [
      "Opens chest, abdomen, and hip flexors",
      "Strengthens the back",
      "Improves posture"
    ],
    "contraindications": [
      "Neck or low back injury",
      "High or low blood pressure",
      "Migraine"
    ],
    "stretchZones": [
      "Front body, chest & quads",
      "Shoulders",
      "Throat & front of neck"
    ]
  },
  {
    "slug": "urdhva-dhanurasana",
    "english": "Wheel Pose",
    "sanskrit": "Urdhva Dhanurasana",
    "category": "Backbends",
    "level": "Advanced",
    "holdSeconds": 20,
    "benefits": [
      "Deeply opens chest, shoulders, and hip flexors",
      "Strengthens arms, legs, and spine",
      "Energizes the body"
    ],
    "contraindications": [
      "Back, wrist, or shoulder injury",
      "High or low blood pressure",
      "Heart conditions"
    ],
    "stretchZones": [
      "Chest & shoulders",
      "Hip flexors",
      "Spine"
    ]
  },
  {
    "slug": "sirsasana",
    "english": "Headstand",
    "sanskrit": "Sirsasana",
    "category": "Inversions",
    "level": "Advanced",
    "holdSeconds": 45,
    "benefits": [
      "Strengthens the core and shoulders",
      "Improves circulation and focus",
      "Calms the mind"
    ],
    "contraindications": [
      "Neck injury",
      "High blood pressure",
      "Glaucoma",
      "Pregnancy"
    ],
    "stretchZones": [
      "Shoulders",
      "Core",
      "Neck"
    ]
  },
  {
    "slug": "adho-mukha-svanasana",
    "english": "Downward-Facing Dog",
    "sanskrit": "Adho Mukha Svanasana",
    "category": "Inversions",
    "level": "Beginner",
    "holdSeconds": 45,
    "benefits": [
      "Stretches hamstrings, calves, and shoulders",
      "Strengthens arms and legs",
      "Energizes the body"
    ],
    "contraindications": [
      "Wrist injury (carpal tunnel)",
      "High blood pressure",
      "Late pregnancy"
    ],
    "stretchZones": [
      "Hamstrings",
      "Calves",
      "Shoulders"
    ]
  },
  {
    "slug": "viparita-karani",
    "english": "Legs Up the Wall",
    "sanskrit": "Viparita Karani",
    "category": "Restorative",
    "level": "Beginner",
    "holdSeconds": 120,
    "benefits": [
      "Relieves tired legs and feet",
      "Calms the mind",
      "Eases mild anxiety and insomnia"
    ],
    "contraindications": [
      "Glaucoma",
      "Serious back or neck issues"
    ],
    "stretchZones": [
      "Legs & feet",
      "Lower back",
      "Nervous system"
    ]
  },
  {
    "slug": "balasana",
    "english": "Child's Pose",
    "sanskrit": "Balasana",
    "category": "Restorative",
    "level": "Beginner",
    "holdSeconds": 60,
    "benefits": [
      "Releases the back and hips",
      "Calms the nervous system",
      "Relieves fatigue"
    ],
    "contraindications": [
      "Knee injury",
      "Pregnancy (widen the knees)",
      "Recent ankle injury"
    ],
    "stretchZones": [
      "Lower back",
      "Hips",
      "Shoulders"
    ]
  },
  {
    "slug": "savasana",
    "english": "Corpse Pose",
    "sanskrit": "Savasana",
    "category": "Restorative",
    "level": "Beginner",
    "holdSeconds": 180,
    "benefits": [
      "Deeply relaxes body and mind",
      "Lowers stress and blood pressure",
      "Integrates the practice"
    ],
    "contraindications": [
      "Late pregnancy (lie on side)",
      "Low back discomfort (bend knees)"
    ],
    "stretchZones": [
      "Full body",
      "Nervous system"
    ]
  },
  {
    "slug": "ardha-hanumanasana",
    "english": "Half Split",
    "sanskrit": "Ardha Hanumanasana",
    "category": "Forward Bends",
    "level": "Intermediate",
    "holdSeconds": 60,
    "benefits": [
      "Stretches hamstrings and calves",
      "Prepares the body for Hanumanasana",
      "Lengthens the spine"
    ],
    "contraindications": [
      "Hamstring tear",
      "Knee sensitivity (pad the back knee)"
    ],
    "stretchZones": [
      "Front-leg hamstring",
      "Calf",
      "Lower back"
    ]
  },
  {
    "slug": "hanumanasana",
    "english": "Front Splits",
    "sanskrit": "Hanumanasana",
    "category": "Hip Openers",
    "level": "Advanced",
    "holdSeconds": 45,
    "benefits": [
      "Deeply stretches hamstrings and hip flexors",
      "Opens the entire lower body",
      "Builds focus and patience"
    ],
    "contraindications": [
      "Hamstring or groin injury",
      "Recent hip surgery",
      "Sacroiliac instability"
    ],
    "stretchZones": [
      "Front-leg hamstring",
      "Back-leg hip flexor & psoas",
      "Inner groin"
    ]
  },
  {
    "slug": "marichyasana-twist",
    "english": "Seated Twist",
    "sanskrit": "Marichyasana",
    "category": "Seated",
    "level": "Intermediate",
    "holdSeconds": 40,
    "benefits": [
      "Improves spinal mobility",
      "Aids digestion",
      "Relieves back tension"
    ],
    "contraindications": [
      "Spinal injury",
      "Pregnancy",
      "Recent abdominal surgery"
    ],
    "stretchZones": [
      "Spine",
      "Outer hip & glute",
      "Chest & shoulders"
    ]
  },
  {
    "slug": "virabhadrasana-iii",
    "english": "Warrior III",
    "sanskrit": "Virabhadrasana III",
    "category": "Standing",
    "level": "Intermediate",
    "holdSeconds": 30,
    "benefits": [
      "Builds balance, focus, and full-body coordination",
      "Strengthens the standing leg, glutes, and back",
      "Tones the core and improves posture"
    ],
    "contraindications": [
      "High blood pressure",
      "Recent ankle or knee injury",
      "Low balance or dizziness (use a wall)"
    ],
    "stretchZones": [
      "Standing leg & glute",
      "Back & core",
      "Lifted-leg hamstring"
    ]
  },
  {
    "slug": "utthita-parsvakonasana",
    "english": "Extended Side Angle",
    "sanskrit": "Utthita Parsvakonasana",
    "category": "Standing",
    "level": "Intermediate",
    "holdSeconds": 40,
    "benefits": [
      "Stretches the side body, groin, and hamstrings",
      "Strengthens the legs, knees, and ankles",
      "Opens the chest and shoulders"
    ],
    "contraindications": [
      "Knee injury (mind front-knee tracking)",
      "High or low blood pressure",
      "Headache or insomnia"
    ],
    "stretchZones": [
      "Side body & waist",
      "Front thigh & groin",
      "Chest & shoulders"
    ]
  },
  {
    "slug": "urdhva-prasarita-eka-padasana",
    "english": "Standing Split",
    "sanskrit": "Urdhva Prasarita Eka Padasana",
    "category": "Standing",
    "level": "Advanced",
    "holdSeconds": 30,
    "benefits": [
      "Deeply stretches the standing-leg hamstring",
      "Builds balance and hip mobility",
      "Strengthens the standing leg and calms the mind"
    ],
    "contraindications": [
      "Hamstring tear or strain",
      "Dizzy spells or low blood pressure",
      "Ankle instability"
    ],
    "stretchZones": [
      "Standing-leg hamstring",
      "Hips",
      "Standing ankle & calf"
    ]
  },
  {
    "slug": "garudasana",
    "english": "Eagle Pose",
    "sanskrit": "Garudasana",
    "category": "Standing",
    "level": "Intermediate",
    "holdSeconds": 30,
    "benefits": [
      "Improves balance and concentration",
      "Stretches the shoulders, upper back, and outer hips",
      "Strengthens the ankles and thighs"
    ],
    "contraindications": [
      "Knee injury (don't hook the foot)",
      "Shoulder injury",
      "Low balance (practice near a wall)"
    ],
    "stretchZones": [
      "Upper back & shoulders",
      "Outer hips",
      "Ankles & thighs"
    ]
  },
  {
    "slug": "gomukhasana",
    "english": "Cow Face Pose",
    "sanskrit": "Gomukhasana",
    "category": "Seated",
    "level": "Intermediate",
    "holdSeconds": 40,
    "benefits": [
      "Opens the shoulders, chest, and triceps",
      "Stretches the outer hips and thighs",
      "Improves posture and upper-body mobility"
    ],
    "contraindications": [
      "Serious shoulder or knee injury",
      "Neck problems (keep the head neutral)"
    ],
    "stretchZones": [
      "Shoulders & triceps",
      "Outer hips & thighs",
      "Chest"
    ]
  },
  {
    "slug": "bharadvajasana",
    "english": "Bharadvaja's Twist",
    "sanskrit": "Bharadvajasana",
    "category": "Seated",
    "level": "Beginner",
    "holdSeconds": 40,
    "benefits": [
      "Gently mobilizes the whole spine",
      "Eases lower-back and neck tension",
      "Aids digestion and calms the mind"
    ],
    "contraindications": [
      "Recent back surgery",
      "Pregnancy (keep it extremely gentle, twisting open)",
      "Acute low-back pain"
    ],
    "stretchZones": [
      "Spine",
      "Outer hips",
      "Chest & shoulders"
    ]
  },
  {
    "slug": "janu-sirsasana",
    "english": "Head-to-Knee Pose",
    "sanskrit": "Janu Sirsasana",
    "category": "Forward Bends",
    "level": "Beginner",
    "holdSeconds": 60,
    "benefits": [
      "Stretches the hamstrings, spine, and outer hip",
      "Calms the nervous system and eases mild anxiety",
      "Improves digestion and flexibility"
    ],
    "contraindications": [
      "Knee injury (support the bent knee)",
      "Acute low-back injury",
      "Diarrhea"
    ],
    "stretchZones": [
      "Extended-leg hamstring",
      "Spine & lower back",
      "Bent-leg outer hip"
    ]
  },
  {
    "slug": "dhanurasana",
    "english": "Bow Pose",
    "sanskrit": "Dhanurasana",
    "category": "Backbends",
    "level": "Intermediate",
    "holdSeconds": 30,
    "benefits": [
      "Opens the entire front body and chest",
      "Strengthens the back muscles and legs",
      "Stretches the hip flexors, quads, and shoulders"
    ],
    "contraindications": [
      "Pregnancy",
      "Wrist injury",
      "High blood pressure",
      "Hernia",
      "Recent abdominal surgery"
    ],
    "stretchZones": [
      "Front body",
      "Quadriceps",
      "Shoulders"
    ]
  },
  {
    "slug": "salabhasana",
    "english": "Locust Pose",
    "sanskrit": "Salabhasana",
    "category": "Backbends",
    "level": "Beginner",
    "holdSeconds": 30,
    "benefits": [
      "Strengthens the back, glutes, and hamstrings",
      "Improves posture and spinal endurance",
      "Gently opens the chest and shoulders"
    ],
    "contraindications": [
      "Pregnancy after the first trimester",
      "Recent abdominal or back surgery",
      "Serious low-back injury"
    ],
    "stretchZones": [
      "Lower back & spine",
      "Glutes & hamstrings",
      "Chest"
    ]
  },
  {
    "slug": "matsyasana",
    "english": "Fish Pose",
    "sanskrit": "Matsyasana",
    "category": "Backbends",
    "level": "Intermediate",
    "holdSeconds": 40,
    "benefits": [
      "Opens the chest, throat, and front of the neck",
      "Counters rounded shoulders and desk posture",
      "Stretches the hip flexors and intercostal muscles"
    ],
    "contraindications": [
      "Neck injury",
      "High or low blood pressure",
      "Migraine or headache"
    ],
    "stretchZones": [
      "Chest & throat",
      "Upper back",
      "Hip flexors"
    ]
  },
  {
    "slug": "mandukasana",
    "english": "Frog Pose",
    "sanskrit": "Mandukasana",
    "category": "Hip Openers",
    "level": "Intermediate",
    "holdSeconds": 75,
    "benefits": [
      "Deeply opens the inner thighs and adductors",
      "Increases hip mobility and external rotation",
      "Relieves tension in the groin and lower back"
    ],
    "contraindications": [
      "Knee injury",
      "Groin strain",
      "Pregnancy"
    ],
    "stretchZones": [
      "Inner thighs & adductors",
      "Hips",
      "Lower back"
    ]
  },
  {
    "slug": "ananda-balasana",
    "english": "Happy Baby Pose",
    "sanskrit": "Ananda Balasana",
    "category": "Hip Openers",
    "level": "Beginner",
    "holdSeconds": 75,
    "benefits": [
      "Gently opens the hips and inner thighs",
      "Releases the lower back and sacrum",
      "Calms the mind and relieves fatigue"
    ],
    "contraindications": [
      "Neck injury (keep the head down)",
      "Pregnancy (use a wide-knee variation)",
      "Recent hip or knee injury"
    ],
    "stretchZones": [
      "Inner thighs & groin",
      "Lower back & sacrum",
      "Hips"
    ]
  },
  {
    "slug": "prasarita-padottanasana",
    "english": "Wide-Legged Forward Fold",
    "sanskrit": "Prasarita Padottanasana",
    "category": "Forward Bends",
    "level": "Beginner",
    "holdSeconds": 60,
    "benefits": [
      "Stretches the hamstrings and inner legs",
      "Releases the spine, neck, and shoulders",
      "Calms the mind and relieves mild fatigue"
    ],
    "contraindications": [
      "Low-back injury (keep a slight bend, come up slowly)",
      "Very low blood pressure",
      "Hamstring tear"
    ],
    "stretchZones": [
      "Hamstrings",
      "Spine & back",
      "Neck & shoulders"
    ]
  },
  {
    "slug": "kumbhakasana",
    "english": "Plank Pose",
    "sanskrit": "Kumbhakasana",
    "category": "Standing",
    "level": "Beginner",
    "holdSeconds": 45,
    "benefits": [
      "Strengthens the core, arms, wrists, and shoulders",
      "Builds full-body stability and endurance",
      "Improves posture and spinal support"
    ],
    "contraindications": [
      "Wrist injury (drop to the forearms)",
      "Pregnancy after the second trimester",
      "Serious shoulder injury"
    ],
    "stretchZones": [
      "Core & abdominals",
      "Shoulders & arms",
      "Wrists"
    ]
  },
  {
    "slug": "vasisthasana",
    "english": "Side Plank Pose",
    "sanskrit": "Vasisthasana",
    "category": "Standing",
    "level": "Intermediate",
    "holdSeconds": 30,
    "benefits": [
      "Strengthens the obliques, wrists, and shoulders",
      "Builds balance and core stability",
      "Tones the arms and improves focus"
    ],
    "contraindications": [
      "Wrist injury (use the forearm version)",
      "Pregnancy after the second trimester",
      "Shoulder injury"
    ],
    "stretchZones": [
      "Obliques & side core",
      "Supporting shoulder & wrist",
      "Chest"
    ]
  },
  {
    "slug": "utkata-konasana",
    "english": "Goddess Pose",
    "sanskrit": "Utkata Konasana",
    "category": "Standing",
    "level": "Beginner",
    "holdSeconds": 45,
    "benefits": [
      "Strengthens the legs, glutes, and pelvic floor",
      "Opens the hips and inner thighs",
      "Builds heat, stamina, and a sense of empowerment"
    ],
    "contraindications": [
      "Knee injury (narrow the stance)",
      "Late pregnancy (mind balance)",
      "Hip injury"
    ],
    "stretchZones": [
      "Inner thighs & groin",
      "Quads & glutes",
      "Pelvic floor & hips"
    ]
  },
  {
    "slug": "viparita-virabhadrasana",
    "english": "Reverse Warrior",
    "sanskrit": "Viparita Virabhadrasana",
    "category": "Standing",
    "level": "Beginner",
    "holdSeconds": 30,
    "benefits": [
      "Stretches the side body, waist, and intercostals",
      "Strengthens the legs and opens the chest",
      "Improves spinal mobility and breath capacity"
    ],
    "contraindications": [
      "Hip or knee injury",
      "Low back injury (keep the arc gentle)",
      "High blood pressure"
    ],
    "stretchZones": [
      "Side body & waist",
      "Front thigh",
      "Chest & shoulders"
    ]
  },
  {
    "slug": "chaturanga-dandasana",
    "english": "Four-Limbed Staff Pose",
    "sanskrit": "Chaturanga Dandasana",
    "category": "Standing",
    "level": "Intermediate",
    "holdSeconds": 8,
    "benefits": [
      "Builds tremendous arm, shoulder, and core strength",
      "Teaches precise shoulder alignment",
      "Prepares the body for arm balances"
    ],
    "contraindications": [
      "Wrist injury",
      "Shoulder impingement",
      "Pregnancy (2nd trimester onward)"
    ],
    "stretchZones": [
      "Shoulders & triceps",
      "Core & abdominals",
      "Wrists"
    ]
  },
  {
    "slug": "urdhva-mukha-svanasana",
    "english": "Upward-Facing Dog",
    "sanskrit": "Urdhva Mukha Svanasana",
    "category": "Backbends",
    "level": "Intermediate",
    "holdSeconds": 20,
    "benefits": [
      "Opens the chest, shoulders, and abdomen",
      "Strengthens the arms, wrists, and spine",
      "Improves posture and counteracts slumping"
    ],
    "contraindications": [
      "Lower back injury",
      "Carpal tunnel syndrome",
      "Pregnancy (2nd trimester onward)"
    ],
    "stretchZones": [
      "Chest & abdomen",
      "Shoulders",
      "Spine"
    ]
  },
  {
    "slug": "marjaryasana-bitilasana",
    "english": "Cat-Cow",
    "sanskrit": "Marjaryasana-Bitilasana",
    "category": "Restorative",
    "level": "Beginner",
    "holdSeconds": 60,
    "benefits": [
      "Mobilizes the whole spine, vertebra by vertebra",
      "Warms up the back before deeper practice",
      "Links breath and movement to settle a busy mind"
    ],
    "contraindications": [
      "Wrist pain (practice on fists or forearms)",
      "Recent spinal injury",
      "Knee sensitivity (pad the knees)"
    ],
    "stretchZones": [
      "Spine",
      "Core & belly",
      "Neck"
    ]
  },
  {
    "slug": "supta-matsyendrasana",
    "english": "Supine Twist",
    "sanskrit": "Supta Matsyendrasana",
    "category": "Restorative",
    "level": "Beginner",
    "holdSeconds": 60,
    "benefits": [
      "Releases the lower back and outer hips",
      "Gently massages the abdominal organs",
      "Downshifts the nervous system before sleep"
    ],
    "contraindications": [
      "Recent spinal or hip surgery",
      "Late pregnancy (twist from the upper back only)",
      "Sacroiliac joint pain"
    ],
    "stretchZones": [
      "Lower back",
      "Outer hip",
      "Chest"
    ]
  },
  {
    "slug": "supta-kapotasana",
    "english": "Reclined Figure-Four",
    "sanskrit": "Supta Kapotasana",
    "category": "Hip Openers",
    "level": "Beginner",
    "holdSeconds": 45,
    "benefits": [
      "Opens the outer hips and glutes deeply but safely",
      "Relieves sciatic and lower-back tension",
      "Perfect after running, cycling, or long sitting"
    ],
    "contraindications": [
      "Recent knee ligament injury",
      "Recent hip replacement (consult your provider)"
    ],
    "stretchZones": [
      "Outer hip & glute",
      "Lower back"
    ]
  },
  {
    "slug": "parsva-balasana",
    "english": "Thread the Needle",
    "sanskrit": "Parsva Balasana",
    "category": "Restorative",
    "level": "Beginner",
    "holdSeconds": 45,
    "benefits": [
      "Releases the upper back and rear shoulder",
      "Gently twists the thoracic spine, where desk stiffness lives",
      "Calms the nervous system with the head supported"
    ],
    "contraindications": [
      "Neck injury (keep the head supported on a block)",
      "Shoulder instability",
      "Knee sensitivity (pad the knees)"
    ],
    "stretchZones": [
      "Upper back",
      "Rear shoulder",
      "Neck"
    ]
  },
  {
    "slug": "uttana-shishosana",
    "english": "Puppy Pose",
    "sanskrit": "Uttana Shishosana",
    "category": "Backbends",
    "level": "Beginner",
    "holdSeconds": 45,
    "benefits": [
      "Opens the shoulders, chest, and armpits",
      "Lengthens the spine without loading the lower back",
      "A gentle first step toward deeper backbends"
    ],
    "contraindications": [
      "Shoulder injury",
      "Knee pain (pad the knees)",
      "Late pregnancy (keep the belly comfortable)"
    ],
    "stretchZones": [
      "Shoulders & armpits",
      "Chest",
      "Mid back"
    ]
  },
  {
    "slug": "malasana",
    "english": "Garland Pose",
    "sanskrit": "Malasana",
    "category": "Hip Openers",
    "level": "Beginner",
    "holdSeconds": 45,
    "benefits": [
      "Opens the hips, groin, and ankles all at once",
      "Counteracts the effects of long sitting",
      "Builds the foundation for splits and deeper hip work"
    ],
    "contraindications": [
      "Knee injury (sit on a block instead)",
      "Achilles or ankle injury",
      "Recent hip surgery"
    ],
    "stretchZones": [
      "Hips & groin",
      "Ankles",
      "Lower back"
    ]
  },
  {
    "slug": "virasana",
    "english": "Hero Pose",
    "sanskrit": "Virasana",
    "category": "Seated",
    "level": "Beginner",
    "holdSeconds": 60,
    "benefits": [
      "Stretches the thighs, knees, and ankles",
      "A steadier meditation seat than crossed legs for many bodies",
      "Improves posture through a naturally upright pelvis"
    ],
    "contraindications": [
      "Knee ligament injury (elevate the seat well)",
      "Ankle injury",
      "Numbness in the legs - come out and shake them free"
    ],
    "stretchZones": [
      "Front thighs",
      "Ankles & feet",
      "Knees"
    ]
  },
  {
    "slug": "supta-baddha-konasana",
    "english": "Reclining Butterfly",
    "sanskrit": "Supta Baddha Konasana",
    "category": "Restorative",
    "level": "Beginner",
    "holdSeconds": 90,
    "benefits": [
      "Opens the inner thighs and groin passively",
      "Deeply calming for the nervous system",
      "A favorite for winding down before sleep"
    ],
    "contraindications": [
      "Groin or knee strain (support the thighs well)",
      "Lower-back discomfort (elevate the torso on a bolster)"
    ],
    "stretchZones": [
      "Inner thighs & groin",
      "Chest",
      "Whole body"
    ]
  },
  {
    "slug": "ardha-matsyendrasana",
    "english": "Half Lord of the Fishes",
    "sanskrit": "Ardha Matsyendrasana",
    "category": "Seated",
    "level": "Intermediate",
    "holdSeconds": 45,
    "benefits": [
      "Increases spinal mobility and digestion",
      "Releases mid-back and shoulder tension",
      "Improves posture after long sitting"
    ],
    "contraindications": [
      "Recent spinal surgery",
      "Herniated disc (keep the twist mild)",
      "Late pregnancy"
    ],
    "stretchZones": [
      "Spine & mid-back",
      "Outer hip",
      "Shoulders"
    ]
  },
  {
    "slug": "upavistha-konasana",
    "english": "Wide-Angle Seated Forward Bend",
    "sanskrit": "Upavistha Konasana",
    "category": "Forward Bends",
    "level": "Beginner",
    "holdSeconds": 60,
    "benefits": [
      "Stretches hamstrings, adductors, and lower back",
      "Calms the nervous system",
      "Prepares the hips for deeper seated work"
    ],
    "contraindications": [
      "Hamstring tear",
      "Groin injury",
      "Lower-back disc issues (fold less and sit higher)"
    ],
    "stretchZones": [
      "Inner thighs",
      "Hamstrings",
      "Lower back"
    ]
  },
  {
    "slug": "halasana",
    "english": "Plow Pose",
    "sanskrit": "Halasana",
    "category": "Inversions",
    "level": "Intermediate",
    "holdSeconds": 45,
    "benefits": [
      "Stretches the spine, shoulders, and hamstrings",
      "Stimulates the thyroid and calming nervous tone",
      "Relieves fatigue when practiced gently"
    ],
    "contraindications": [
      "Neck injury",
      "Glaucoma or high blood pressure",
      "Menstruation (skip deep inversions)",
      "Pregnancy"
    ],
    "stretchZones": [
      "Spine & back body",
      "Shoulders",
      "Hamstrings"
    ]
  },
  {
    "slug": "sarvangasana",
    "english": "Shoulder Stand",
    "sanskrit": "Salamba Sarvangasana",
    "category": "Inversions",
    "level": "Intermediate",
    "holdSeconds": 45,
    "benefits": [
      "Strengthens shoulders, arms, and core",
      "Improves circulation and focus",
      "Deeply calming when held with support"
    ],
    "contraindications": [
      "Neck injury",
      "Glaucoma",
      "High blood pressure",
      "Menstruation",
      "Pregnancy"
    ],
    "stretchZones": [
      "Shoulders & upper arms",
      "Core",
      "Neck"
    ]
  },
  {
    "slug": "bakasana",
    "english": "Crow Pose",
    "sanskrit": "Bakasana",
    "category": "Standing",
    "level": "Advanced",
    "holdSeconds": 20,
    "benefits": [
      "Strengthens arms, wrists, and core",
      "Improves balance and concentration",
      "Builds confidence for deeper arm balances"
    ],
    "contraindications": [
      "Wrist injury",
      "Shoulder instability",
      "Pregnancy",
      "Recent carpal tunnel flare"
    ],
    "stretchZones": [
      "Arms & wrists",
      "Core",
      "Inner thighs"
    ]
  },
  {
    "slug": "parivrtta-anjaneyasana",
    "english": "Revolved Low Lunge",
    "sanskrit": "Parivrtta Anjaneyasana",
    "category": "Standing",
    "level": "Intermediate",
    "holdSeconds": 30,
    "benefits": [
      "Opens hip flexors and chest",
      "Builds balance and spinal mobility",
      "Energizes a sluggish mid-day body"
    ],
    "contraindications": [
      "Knee injury (pad generously)",
      "Recent spinal injury",
      "Late pregnancy"
    ],
    "stretchZones": [
      "Hip flexors",
      "Spine",
      "Chest"
    ]
  },
  {
    "slug": "purvottanasana",
    "english": "Upward Plank",
    "sanskrit": "Purvottanasana",
    "category": "Backbends",
    "level": "Intermediate",
    "holdSeconds": 30,
    "benefits": [
      "Strengthens wrists, arms, and posterior chain",
      "Opens the chest and shoulders",
      "Counters long hours of sitting and typing"
    ],
    "contraindications": [
      "Wrist injury",
      "Shoulder injury",
      "Neck pain (keep the head neutral)"
    ],
    "stretchZones": [
      "Front body",
      "Arms & wrists",
      "Glutes & hamstrings"
    ]
  },
  {
    "slug": "apanasana",
    "english": "Knees-to-Chest Pose",
    "sanskrit": "Apanasana",
    "category": "Restorative",
    "level": "Beginner",
    "holdSeconds": 60,
    "benefits": [
      "Relieves lower-back tension",
      "Gently massages the abdominal organs",
      "A reset button between stronger poses"
    ],
    "contraindications": [
      "Recent abdominal surgery",
      "Late pregnancy (widen the knees)",
      "Severe knee issues"
    ],
    "stretchZones": [
      "Lower back",
      "Hips",
      "Belly"
    ]
  },
  {
    "slug": "supta-padangusthasana",
    "english": "Reclined Hand-to-Big-Toe",
    "sanskrit": "Supta Padangusthasana",
    "category": "Forward Bends",
    "level": "Beginner",
    "holdSeconds": 45,
    "benefits": [
      "Lengthens hamstrings and calves safely",
      "Relieves sciatic tension for many bodies",
      "Improves leg flexibility for standing folds"
    ],
    "contraindications": [
      "Hamstring tear",
      "Acute sciatica (keep the stretch mild)",
      "Unstable SI joint"
    ],
    "stretchZones": [
      "Hamstrings",
      "Calves",
      "Hip"
    ]
  },
  {
    "slug": "parighasana",
    "english": "Gate Pose",
    "sanskrit": "Parighasana",
    "category": "Standing",
    "level": "Beginner",
    "holdSeconds": 30,
    "benefits": [
      "Stretches the side body and intercostals",
      "Opens the outer hip and hamstring of the extended leg",
      "Improves breathing capacity"
    ],
    "contraindications": [
      "Knee injury (pad well or practice seated)",
      "Recent rib injury"
    ],
    "stretchZones": [
      "Side body",
      "Inner thigh",
      "Ribs"
    ]
  },
  {
    "slug": "ardha-pincha-mayurasana",
    "english": "Dolphin Pose",
    "sanskrit": "Ardha Pincha Mayurasana",
    "category": "Inversions",
    "level": "Intermediate",
    "holdSeconds": 45,
    "benefits": [
      "Builds shoulder and upper-back strength",
      "Stretches hamstrings and calves",
      "Safe prep for forearm stand and headstand"
    ],
    "contraindications": [
      "Shoulder injury",
      "Wrist-free alternative still loads elbows — ease off if painful",
      "High blood pressure (keep the head high)"
    ],
    "stretchZones": [
      "Shoulders",
      "Hamstrings",
      "Upper back"
    ]
  },
  {
    "slug": "parivrtta-trikonasana",
    "english": "Revolved Triangle",
    "sanskrit": "Parivrtta Trikonasana",
    "category": "Standing",
    "level": "Intermediate",
    "holdSeconds": 30,
    "benefits": [
      "Improves balance and proprioception",
      "Stretches hamstrings and IT band",
      "Strengthens legs and deep core"
    ],
    "contraindications": [
      "Low back injury",
      "Tight hamstrings (use a block)",
      "Migraine or dizziness"
    ],
    "stretchZones": [
      "Hamstrings",
      "Spine",
      "Standing legs"
    ]
  },
  {
    "slug": "natarajasana",
    "english": "Dancer Pose",
    "sanskrit": "Natarajasana",
    "category": "Standing",
    "level": "Intermediate",
    "holdSeconds": 30,
    "benefits": [
      "Improves balance and focus",
      "Opens the chest, shoulders, and hip flexors",
      "Strengthens the standing leg"
    ],
    "contraindications": [
      "Ankle or knee instability",
      "Low back pain (kick less)",
      "Shoulder injury"
    ],
    "stretchZones": [
      "Standing leg",
      "Hip flexors & chest",
      "Shoulders"
    ]
  },
  {
    "slug": "agnistambhasana",
    "english": "Fire Log Pose",
    "sanskrit": "Agnistambhasana",
    "category": "Hip Openers",
    "level": "Intermediate",
    "holdSeconds": 60,
    "benefits": [
      "Deeply opens the outer hips and glutes",
      "Relieves tension from sitting and running",
      "Prepares the hips for lotus and pigeon variations"
    ],
    "contraindications": [
      "Knee injury (never force the stack)",
      "Hip replacement",
      "Acute SI joint pain"
    ],
    "stretchZones": [
      "Outer hips & glutes",
      "Groin",
      "Lower back"
    ]
  },
  {
    "slug": "salamba-bhujangasana",
    "english": "Sphinx Pose",
    "sanskrit": "Salamba Bhujangasana",
    "category": "Backbends",
    "level": "Beginner",
    "holdSeconds": 60,
    "benefits": [
      "Gently strengthens the lower back",
      "Opens the chest and throat",
      "A safe starting point for deeper backbends"
    ],
    "contraindications": [
      "Acute lower-back flare (keep very low)",
      "Wrist-free and elbow-friendly — still ease off if painful"
    ],
    "stretchZones": [
      "Lower back",
      "Chest & throat",
      "Shoulders"
    ]
  },
  {
    "slug": "skandasana",
    "english": "Side Lunge",
    "sanskrit": "Skandasana",
    "category": "Hip Openers",
    "level": "Intermediate",
    "holdSeconds": 30,
    "benefits": [
      "Opens adductors and hips",
      "Strengthens quads and glutes",
      "Builds mobility for squats and wide-legged poses"
    ],
    "contraindications": [
      "Knee injury",
      "Groin strain",
      "Ankle instability"
    ],
    "stretchZones": [
      "Inner thighs",
      "Hips",
      "Ankles"
    ]
  },
  {
    "slug": "makarasana",
    "english": "Crocodile Pose",
    "sanskrit": "Makarasana",
    "category": "Restorative",
    "level": "Beginner",
    "holdSeconds": 90,
    "benefits": [
      "Releases lower-back and sacral tension",
      "Encourages natural diaphragmatic breath",
      "A quiet alternative to Savasana for some bodies"
    ],
    "contraindications": [
      "Pregnancy (skip prone poses)",
      "Recent abdominal surgery",
      "Difficulty lying on the belly"
    ],
    "stretchZones": [
      "Lower back",
      "Belly",
      "Whole body"
    ]
  }
];

export const COACH_CATALOG_SLUGS = new Set(COACH_CATALOG.map((p) => p.slug));

// Compact one-line-per-pose JSON string bundled into the system prompt.
export const COACH_CATALOG_JSON = JSON.stringify(
  COACH_CATALOG.map((p) => ({
    slug: p.slug,
    english: p.english,
    sanskrit: p.sanskrit,
    category: p.category,
    level: p.level,
    holdSeconds: p.holdSeconds,
    benefits: p.benefits,
    contraindications: p.contraindications,
    stretchZones: p.stretchZones,
  })),
);
