/**
 * Generate English WebVTT captions for every asana how-to clip.
 *
 * Writes client/public/captions/poses/{slug}.vtt from the pose's spoken steps
 * so the demo video can show coaching cues without inventing CDN URLs.
 *
 * Timing is evenly spaced across a short demo window (matches journey length).
 * Real voice timing lives in voice/timings/{slug}.timing.json when generated.
 *
 * Usage:
 *   npx tsx script/gen-pose-captions.ts
 *   npx tsx script/gen-pose-captions.ts --force
 *   npx tsx script/gen-pose-captions.ts --only tadasana
 */
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { ASANAS } from "../client/src/data/content.ts";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const OUT_DIR = path.join(ROOT, "client/public/captions/poses");
const READY_FILE = path.join(ROOT, "client/src/data/poseCaptionsReady.generated.ts");

/** Demo caption window — aligned with typical step-journey clip length. */
const WINDOW_SECONDS = 8;

type Args = { force: boolean; only: string | null };

function parseArgs(argv: string[]): Args {
  const args: Args = { force: false, only: null };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--force") args.force = true;
    else if (a === "--only") args.only = argv[++i] ?? null;
  }
  return args;
}

function pad(n: number): string {
  return String(Math.floor(n)).padStart(2, "0");
}

function formatTs(seconds: number): string {
  const s = Math.max(0, seconds);
  const h = Math.floor(s / 3600);
  const m = Math.floor((s % 3600) / 60);
  const sec = s % 60;
  const whole = Math.floor(sec);
  const ms = Math.round((sec - whole) * 1000);
  return `${pad(h)}:${pad(m)}:${pad(whole)}.${String(ms).padStart(3, "0")}`;
}

function escapeVtt(text: string): string {
  return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function buildVtt(steps: { text: string }[]): string {
  const lines = ["WEBVTT", ""];
  const n = Math.max(1, steps.length);
  const slice = WINDOW_SECONDS / n;
  for (let i = 0; i < n; i++) {
    const start = i * slice;
    const end = i === n - 1 ? WINDOW_SECONDS : (i + 1) * slice;
    const text = steps[i]?.text?.trim() || `Step ${i + 1}`;
    lines.push(String(i + 1));
    lines.push(`${formatTs(start)} --> ${formatTs(end)}`);
    lines.push(escapeVtt(text));
    lines.push("");
  }
  return lines.join("\n");
}

async function fileNonEmpty(p: string): Promise<boolean> {
  try {
    const st = await fs.stat(p);
    return st.isFile() && st.size > 0;
  } catch {
    return false;
  }
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  await fs.mkdir(OUT_DIR, { recursive: true });

  let asanas = [...ASANAS];
  if (args.only) {
    asanas = asanas.filter((a) => a.slug === args.only);
    if (!asanas.length) throw new Error(`Unknown asana slug: ${args.only}`);
  }

  let written = 0;
  let skipped = 0;
  for (const asana of asanas) {
    const out = path.join(OUT_DIR, `${asana.slug}.vtt`);
    if (!args.force && (await fileNonEmpty(out))) {
      skipped++;
      continue;
    }
    await fs.writeFile(out, buildVtt(asana.steps), "utf8");
    written++;
  }

  const ready: string[] = [];
  for (const a of ASANAS) {
    if (await fileNonEmpty(path.join(OUT_DIR, `${a.slug}.vtt`))) ready.push(a.slug);
  }
  const body = `/**
 * AUTO-GENERATED by script/gen-pose-captions.ts — do not edit by hand.
 * Re-run: npx tsx script/gen-pose-captions.ts
 */
export const POSE_CAPTIONS_READY_LIST = ${JSON.stringify(ready, null, 2)} as const;
`;
  await fs.writeFile(READY_FILE, body, "utf8");

  console.log(
    `Captions: wrote ${written}, skipped ${skipped}. Registered ${ready.length} in ${path.relative(ROOT, READY_FILE)}`,
  );
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
