// Generates server/coach-catalog.ts — a compact, self-contained JSON catalog
// of the 29 asanas (excludes pathway entries + breathing techniques) used by
// the AI Yoga Coach compose endpoint. Run: npx tsx script/gen-coach-catalog.ts
import { writeFileSync } from "node:fs";
import { ASANAS, type Category, type Difficulty } from "../client/src/data/content";

// Category -> "level" grouping is already on each asana as `difficulty`.
type CatalogPose = {
  slug: string;
  english: string;
  sanskrit: string;
  category: Category;
  level: Difficulty;
  holdSeconds: number;
  benefits: string[];
  contraindications: string[];
  stretchZones: string[];
};

// The 29 real asanas are the ASANAS whose slug is not a pathway/breathing entry.
// content.ts ASANAS already contains only the pose library (pathways + breathing
// live in separate arrays), so we take them all.
const catalog: CatalogPose[] = ASANAS.map((a) => ({
  slug: a.slug,
  english: a.english,
  sanskrit: a.sanskrit,
  category: a.category,
  level: a.difficulty,
  holdSeconds: a.holdSeconds,
  benefits: a.benefits,
  contraindications: a.contraindications,
  stretchZones: (a.stretchZones || []).map((z) => z.region),
}));

const header = `// AUTO-GENERATED by script/gen-coach-catalog.ts — do not edit by hand.
// Compact pose catalog for the AI Yoga Coach compose endpoint (v4).
export type CoachPose = {
  slug: string;
  english: string;
  sanskrit: string;
  category: string;
  level: string;
  holdSeconds: number;
  benefits: string[];
  contraindications: string[];
  stretchZones: string[];
};

export const COACH_CATALOG: CoachPose[] = ${JSON.stringify(catalog, null, 2)};

export const COACH_CATALOG_SLUGS = new Set(COACH_CATALOG.map((p) => p.slug));

// Compact one-line-per-pose JSON string bundled into the system prompt.
export const COACH_CATALOG_JSON = JSON.stringify(
  COACH_CATALOG.map((p) => ({
    slug: p.slug,
    english: p.english,
    sanskrit: p.sanskrit,
    category: p.category,
    level: p.level,
    holdSeconds: p.holdSeconds,
    benefits: p.benefits,
    contraindications: p.contraindications,
    stretchZones: p.stretchZones,
  })),
);
`;

writeFileSync(new URL("../server/coach-catalog.ts", import.meta.url), header);
console.log(`Wrote server/coach-catalog.ts with ${catalog.length} poses.`);
console.log("slugs:", catalog.map((c) => c.slug).join(", "));
