/**
 * Generate short looping demo videos from pose PNG illustrations.
 *
 * For each `client/public/poses/{slug}.png` (excluding `_`-prefixed assets),
 * writes:
 *   client/public/videos/poses/{slug}.webm
 *   client/public/videos/poses/{slug}.mp4
 *
 * Then regenerates `client/src/data/poseVideosReady.generated.ts` so the UI
 * can enable video without probing for missing files.
 *
 * Usage:
 *   npx tsx script/gen-pose-videos.ts
 *   npx tsx script/gen-pose-videos.ts --force          # regenerate all
 *   npx tsx script/gen-pose-videos.ts --only tadasana  # one slug
 *   npx tsx script/gen-pose-videos.ts --concurrency 6
 *
 * Requires ffmpeg on PATH (e.g. `brew install ffmpeg`).
 */

import { spawn } from "node:child_process";
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const POSES_DIR = path.join(ROOT, "client/public/poses");
const OUT_DIR = path.join(ROOT, "client/public/videos/poses");
const READY_FILE = path.join(ROOT, "client/src/data/poseVideosReady.generated.ts");

const DURATION_SEC = 5;
const FPS = 24;
const WIDTH = 600;
const HEIGHT = 1200;
const FRAMES = DURATION_SEC * FPS;

type Args = {
  force: boolean;
  only: string | null;
  concurrency: number;
  skipMp4: boolean;
};

function parseArgs(argv: string[]): Args {
  const args: Args = { force: false, only: null, concurrency: 4, skipMp4: false };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--force") args.force = true;
    else if (a === "--skip-mp4") args.skipMp4 = true;
    else if (a === "--only") args.only = argv[++i] ?? null;
    else if (a === "--concurrency") {
      const n = Number(argv[++i]);
      if (Number.isFinite(n) && n >= 1) args.concurrency = Math.floor(n);
    } else if (a === "--help" || a === "-h") {
      console.log(`Usage: npx tsx script/gen-pose-videos.ts [--force] [--only slug] [--concurrency N] [--skip-mp4]`);
      process.exit(0);
    }
  }
  return args;
}

function run(cmd: string, args: string[]): Promise<void> {
  return new Promise((resolve, reject) => {
    const child = spawn(cmd, args, { stdio: ["ignore", "ignore", "pipe"] });
    let err = "";
    child.stderr?.on("data", (d) => {
      err += String(d);
    });
    child.on("error", reject);
    child.on("close", (code) => {
      if (code === 0) resolve();
      else reject(new Error(`${cmd} exited ${code}\n${err.slice(-800)}`));
    });
  });
}

async function ensureFfmpeg(): Promise<void> {
  try {
    await run("ffmpeg", ["-version"]);
  } catch {
    throw new Error("ffmpeg not found on PATH. Install with: brew install ffmpeg");
  }
}

/** Subtle breathing zoom that returns to the start scale for a seamless loop. */
function vfFilter(): string {
  const z = `1.03+0.025*sin(2*PI*on/${FRAMES})`;
  return [
    `scale=${WIDTH}:${HEIGHT}:force_original_aspect_ratio=decrease`,
    `pad=${WIDTH}:${HEIGHT}:(ow-iw)/2:(oh-ih)/2`,
    `zoompan=z='${z}':x='iw/2-(iw/zoom/2)':y='ih/2-(ih/zoom/2)':d=1:s=${WIDTH}x${HEIGHT}:fps=${FPS}`,
    "format=yuv420p",
  ].join(",");
}

async function encodeWebm(png: string, out: string): Promise<void> {
  await run("ffmpeg", [
    "-y",
    "-loop", "1",
    "-i", png,
    "-vf", vfFilter(),
    "-t", String(DURATION_SEC),
    "-an",
    "-c:v", "libvpx-vp9",
    "-b:v", "250k",
    "-crf", "36",
    "-row-mt", "1",
    "-deadline", "good",
    "-cpu-used", "4",
    out,
  ]);
}

async function encodeMp4(png: string, out: string): Promise<void> {
  await run("ffmpeg", [
    "-y",
    "-loop", "1",
    "-i", png,
    "-vf", vfFilter(),
    "-t", String(DURATION_SEC),
    "-an",
    "-c:v", "libx264",
    "-pix_fmt", "yuv420p",
    "-profile:v", "baseline",
    "-level", "3.1",
    "-crf", "28",
    "-preset", "veryfast",
    "-movflags", "+faststart",
    out,
  ]);
}

async function fileNonEmpty(p: string): Promise<boolean> {
  try {
    const st = await fs.stat(p);
    return st.isFile() && st.size > 0;
  } catch {
    return false;
  }
}

async function listPoseSlugs(): Promise<string[]> {
  const entries = await fs.readdir(POSES_DIR);
  return entries
    .filter((f) => f.endsWith(".png") && !f.startsWith("_"))
    .map((f) => f.replace(/\.png$/, ""))
    .sort();
}

async function writeReadyList(slugs: string[]): Promise<void> {
  const body = `/**
 * AUTO-GENERATED by script/gen-pose-videos.ts — do not edit by hand.
 * Re-run: npx tsx script/gen-pose-videos.ts
 */
export const POSE_VIDEOS_READY_LIST = ${JSON.stringify(slugs, null, 2)} as const;
`;
  await fs.writeFile(READY_FILE, body, "utf8");
}

async function mapPool<T>(
  items: T[],
  concurrency: number,
  fn: (item: T, index: number) => Promise<void>,
): Promise<{ ok: number; failed: { item: T; error: string }[] }> {
  let ok = 0;
  const failed: { item: T; error: string }[] = [];
  let next = 0;

  async function worker() {
    while (next < items.length) {
      const i = next++;
      const item = items[i]!;
      try {
        await fn(item, i);
        ok++;
      } catch (e) {
        failed.push({ item, error: e instanceof Error ? e.message : String(e) });
      }
    }
  }

  await Promise.all(
    Array.from({ length: Math.min(concurrency, items.length) }, () => worker()),
  );
  return { ok, failed };
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  await ensureFfmpeg();
  await fs.mkdir(OUT_DIR, { recursive: true });

  let slugs = await listPoseSlugs();
  if (args.only) {
    if (!slugs.includes(args.only)) {
      throw new Error(`Unknown pose slug (no PNG): ${args.only}`);
    }
    slugs = [args.only];
  }

  console.log(
    `Generating pose videos for ${slugs.length} pose(s) ` +
      `(concurrency=${args.concurrency}, force=${args.force}, mp4=${!args.skipMp4})…`,
  );

  const started = Date.now();
  let skipped = 0;

  const { ok, failed } = await mapPool(slugs, args.concurrency, async (slug, index) => {
    const png = path.join(POSES_DIR, `${slug}.png`);
    const webm = path.join(OUT_DIR, `${slug}.webm`);
    const mp4 = path.join(OUT_DIR, `${slug}.mp4`);

    const needWebm = args.force || !(await fileNonEmpty(webm));
    const needMp4 = !args.skipMp4 && (args.force || !(await fileNonEmpty(mp4)));

    if (!needWebm && !needMp4) {
      skipped++;
      return;
    }

    if (needWebm) await encodeWebm(png, webm);
    if (needMp4) await encodeMp4(png, mp4);

    if ((index + 1) % 10 === 0 || index === 0 || index === slugs.length - 1) {
      console.log(`  [${index + 1}/${slugs.length}] ${slug}`);
    }
  });

  // Ready list = every pose that has a non-empty webm (full inventory when batch succeeds).
  const allSlugs = await listPoseSlugs();
  const ready: string[] = [];
  for (const slug of allSlugs) {
    if (await fileNonEmpty(path.join(OUT_DIR, `${slug}.webm`))) ready.push(slug);
  }
  await writeReadyList(ready);

  const secs = ((Date.now() - started) / 1000).toFixed(1);
  console.log(
    `\nDone in ${secs}s — encoded/updated ${ok}, skipped existing ${skipped}, failed ${failed.length}.`,
  );
  console.log(`Registered ${ready.length} slugs in ${path.relative(ROOT, READY_FILE)}`);
  if (failed.length) {
    console.error("Failures:");
    for (const f of failed) console.error(`  - ${f.item}: ${f.error.split("\n")[0]}`);
    process.exitCode = 1;
  }
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
