/**
 * Generate short looping demo videos from kids pose PNG illustrations.
 *
 * For each entry in kids.ts with a matching `client/public/kids/{image}.png`,
 * writes:
 *   client/public/videos/kids/{slug}.webm
 *   client/public/videos/kids/{slug}.mp4
 *
 * Then regenerates `client/src/data/kidsVideosReady.generated.ts`.
 *
 * Usage:
 *   npx tsx script/gen-kids-pose-videos.ts
 *   npx tsx script/gen-kids-pose-videos.ts --force
 */
import { spawn } from "node:child_process";
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { KIDS_POSES } from "../client/src/data/kids.ts";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const KIDS_DIR = path.join(ROOT, "client/public/kids");
const OUT_DIR = path.join(ROOT, "client/public/videos/kids");
const READY_FILE = path.join(ROOT, "client/src/data/kidsVideosReady.generated.ts");

const DURATION_SEC = 5;
const FPS = 24;
const WIDTH = 640;
const HEIGHT = 640;
const FRAMES = DURATION_SEC * FPS;

const force = process.argv.includes("--force");

function run(cmd: string, args: string[]): Promise<void> {
  return new Promise((resolve, reject) => {
    const child = spawn(cmd, args, { stdio: ["ignore", "ignore", "pipe"] });
    let err = "";
    child.stderr?.on("data", (d) => {
      err += String(d);
    });
    child.on("error", reject);
    child.on("close", (code) => {
      if (code === 0) resolve();
      else reject(new Error(`${cmd} exited ${code}\n${err.slice(-800)}`));
    });
  });
}

function vfFilter(): string {
  const z = `1.04+0.03*sin(2*PI*on/${FRAMES})`;
  return [
    `scale=${WIDTH}:${HEIGHT}:force_original_aspect_ratio=decrease`,
    `pad=${WIDTH}:${HEIGHT}:(ow-iw)/2:(oh-ih)/2`,
    `zoompan=z='${z}':x='iw/2-(iw/zoom/2)':y='ih/2-(ih/zoom/2)':d=1:s=${WIDTH}x${HEIGHT}:fps=${FPS}`,
    "format=yuv420p",
  ].join(",");
}

async function fileNonEmpty(p: string): Promise<boolean> {
  try {
    const st = await fs.stat(p);
    return st.isFile() && st.size > 0;
  } catch {
    return false;
  }
}

async function encodeWebm(png: string, out: string): Promise<void> {
  await run("ffmpeg", [
    "-y", "-loop", "1", "-i", png,
    "-vf", vfFilter(), "-t", String(DURATION_SEC), "-an",
    "-c:v", "libvpx-vp9", "-b:v", "220k", "-crf", "36",
    "-row-mt", "1", "-deadline", "good", "-cpu-used", "4", out,
  ]);
}

async function encodeMp4(png: string, out: string): Promise<void> {
  await run("ffmpeg", [
    "-y", "-loop", "1", "-i", png,
    "-vf", vfFilter(), "-t", String(DURATION_SEC), "-an",
    "-c:v", "libx264", "-pix_fmt", "yuv420p", "-profile:v", "baseline",
    "-level", "3.1", "-crf", "28", "-preset", "veryfast",
    "-movflags", "+faststart", out,
  ]);
}

async function main() {
  await run("ffmpeg", ["-version"]);
  await fs.mkdir(OUT_DIR, { recursive: true });

  const ready: string[] = [];
  let encoded = 0;
  let skipped = 0;

  for (const pose of KIDS_POSES) {
    const png = path.join(KIDS_DIR, `${pose.image}.png`);
    if (!(await fileNonEmpty(png))) {
      console.warn(`  skip ${pose.slug}: missing ${pose.image}.png`);
      continue;
    }
    const webm = path.join(OUT_DIR, `${pose.slug}.webm`);
    const mp4 = path.join(OUT_DIR, `${pose.slug}.mp4`);
    const need = force || !(await fileNonEmpty(webm)) || !(await fileNonEmpty(mp4));
    if (need) {
      await encodeWebm(png, webm);
      await encodeMp4(png, mp4);
      encoded++;
      console.log(`  [${encoded}] ${pose.slug}`);
    } else {
      skipped++;
    }
    if (await fileNonEmpty(webm)) ready.push(pose.slug);
  }

  const body = `/**
 * AUTO-GENERATED by script/gen-kids-pose-videos.ts — do not edit by hand.
 * Re-run: npx tsx script/gen-kids-pose-videos.ts
 */
export const KIDS_VIDEOS_READY_LIST = ${JSON.stringify(ready, null, 2)} as const;
`;
  await fs.writeFile(READY_FILE, body, "utf8");
  console.log(`\nEncoded ${encoded}, skipped ${skipped}, registered ${ready.length}.`);
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
