/**
 * AUTO-GENERATED by script/gen-pose-thumbs.ts — do not edit by hand.
 * Re-run: npx tsx script/gen-pose-thumbs.ts
 *
 * Empty until the generator is run. `PoseImage thumb` consults this list
 * rather than requesting /poses/thumbs/<slug> optimistically — an optional
 * asset that does not exist should not cost a 404 on every list render.
 */
export const POSE_THUMBS_READY_LIST: string[] = [];
